import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const ops = read('lib/ops/client.ts')
const route = read('app/api/v1/website/pricing/preview/route.ts')
const application = read('app/(public)/teckna-avtal/page.tsx')

assert.ok(ops.includes('"/api/v1/website/public-contracts"'))
assert.ok(ops.includes('"/api/v1/website/public-contracts/diagnostics"'))
assert.ok(ops.includes('"/api/v1/website/quote"'))
assert.ok(ops.includes('"/api/v1/website/customer-applications"'))
assert.ok(ops.includes('"/api/v1/integration/context"'))
assert.ok(!ops.includes('opsFetchWithFallback'))
assert.ok(route.includes('annual_consumption_kwh: annualKwh'))
assert.ok(route.includes('grid_area_code: gridAreaCode'))
assert.ok(route.includes('websitePricingPreviewSource(preview)'))
assert.ok(application.includes('quote_reference: verifiedQuote.quote.quote_reference'))
assert.ok(application.includes('grid_area_code: serverResolution?.grid_area_code'))
assert.ok(!application.includes('price_plan_id'))
console.log('Gridex API contract alignment checks passed')
