import assert from 'node:assert/strict'
import fs from 'node:fs'
const read = (p) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8')
const ops = read('lib/ops/client.ts')
const pricing = read('lib/website/pricingPreview.ts')
const area = read('app/api/v1/website/energy/resolve/route.ts')
const publicPage = read('app/(public)/page.tsx')
const signupPage = read('app/(public)/teckna-avtal/page.tsx')
const readiness = read('lib/ops/readiness.ts')
assert.ok(!ops.includes('/api/v1/website/quote'))
assert.ok(!ops.includes('/api/v1/website/energy-area/resolve'))
assert.ok(!ops.includes('validateOpsWebsiteQuote'))
assert.ok(!ops.includes('pricing_snapshot_reference: input.pricing_snapshot_reference'))
assert.ok(pricing.includes('fetchMonthlySpotAverageFromElprisetJustNu'))
assert.ok(pricing.includes('ops_fixed_price_by_resolved_area'))
assert.ok(area.includes('resolveWebsitePriceAreaForPricing'))
assert.ok(publicPage.includes('item.type === "fixed" ? null'))
assert.ok(signupPage.includes('item.type === "fixed" ? null'))
assert.ok(!readiness.includes('website_quotes.write'))
assert.ok(!readiness.includes('website_energy_area.resolve'))
assert.ok(read('lib/website/customerType.ts').includes("'private' | 'business'"))
console.log('Website API 2026-07-22.2 contract tests passed')
