// Generated from eSett Public Data Portal network area list supplied to the project.
// Used only for website pricing preview area resolution.
// Do not treat this data as verified facility/grid owner truth.

export type WebsiteGridPriceArea = 'SE1' | 'SE2' | 'SE3' | 'SE4'

export type WebsiteGridAreaPriceAreaRow = {
  priceArea: WebsiteGridPriceArea
  label: string
}

export const WEBSITE_GRID_AREA_PRICE_AREAS: Record<string, WebsiteGridAreaPriceAreaRow> = {
  "PIB": { priceArea: "SE1", label: "AB Piteenergi Pitebygden" },
  "KKA": { priceArea: "SE4", label: "Aff\u00e4rsverken Eln\u00e4t AB Karlskrona" },
  "LED": { priceArea: "SE3", label: "Ale Elf\u00f6rening ek f\u00f6r Lilla Edet-Ale" },
  "ALS": { priceArea: "SE3", label: "Alings\u00e5s Energi N\u00e4t Ab Alings\u00e5s" },
  "AMS": { priceArea: "SE3", label: "Almn\u00e4s Bruk AB Almn\u00e4s" },
  "ALV": { priceArea: "SE4", label: "Alvesta Eln\u00e4t AB Alvesta K\u00f6ping" },
  "ARV": { priceArea: "SE3", label: "Arvika Teknik AB Arvika" },
  "BAC": { priceArea: "SE4", label: "Baltic Cable AB BAC" },
  "BEF": { priceArea: "SE3", label: "Bengtsfors Energi N\u00e4t AB Bengtsfors" },
  "BRG": { priceArea: "SE2", label: "Bergs tingslags elektriska AB Berg" },
  "KNS": { priceArea: "SE3", label: "BillerudKorsn\u00e4s Skog & Industri AB, G\u00e4vle Korsn\u00e4s" },
  "BJR": { priceArea: "SE4", label: "Bj\u00e4re Kraft ek f\u00f6r Bj\u00e4re" },
  "BKE": { priceArea: "SE3", label: "Bj\u00e4rke Energi Ek. F\u00f6r. Bj\u00e4rke" },
  "BLI": { priceArea: "SE2", label: "Bliekevare N\u00e4t AB Bliekevare" },
  "FRV": { priceArea: "SE2", label: "Bl\u00e5sj\u00f6n N\u00e4t AB Frostviken region" },
  "KNP": { priceArea: "SE3", label: "Boda N\u00e4t ekonomiska f\u00f6rening Kn\u00e4pplan" },
  "BDN": { priceArea: "SE1", label: "Bodens Energi N\u00e4t AB Boden" },
  "BOO": { priceArea: "SE3", label: "Boo Energi ek. f\u00f6r Boo" },
  "BHM": { priceArea: "SE4", label: "Borgholm Energi Eln\u00e4t AB Borgholm" },
  "BRL": { priceArea: "SE3", label: "Borl\u00e4nge Energi Eln\u00e4t AB Borl\u00e4nge" },
  "BRS": { priceArea: "SE3", label: "Bor\u00e5s Eln\u00e4t AB Bor\u00e5s" },
  "BDL": { priceArea: "SE4", label: "Brittedals Eln\u00e4t ek f\u00f6r Brittedal" },
  "KVI": { priceArea: "SE4", label: "Brittedals Eln\u00e4t ek f\u00f6r Kviinge" },
  "BBN": { priceArea: "SE1", label: "Brobacken N\u00e4t AB Brobacken" },
  "BMA": { priceArea: "SE4", label: "Brom\u00f6lla Energi & Vatten AB Brom\u00f6lla" },
  "BLN": { priceArea: "SE1", label: "Br\u00e4nnliden N\u00e4t AB Br\u00e4nnliden" },
  "KRS": { priceArea: "SE4", label: "C4 Eln\u00e4t AB Kristianstad-\u00c5hus" },
  "CBR": { priceArea: "SE3", label: "Carlfors Bruk AB Carlfors Bruk" },
  "GNF": { priceArea: "SE3", label: "Dala Energi Eln\u00e4t AB Gagnef" },
  "LER": { priceArea: "SE3", label: "Dala Energi Eln\u00e4t AB Leksand-R\u00e4ttvik" },
  "STR": { priceArea: "SE3", label: "Dala Energi Eln\u00e4t AB S\u00e4ter" },
  "DFS": { priceArea: "SE3", label: "Degerfors Energi AB Degerfors" },
  "DLN": { priceArea: "SE1", label: "Dragaliden Net AB Dragaliden" },
  "BLE": { priceArea: "SE4", label: "E.ON Energidistribution AB Blekinge" },
  "DAN": { priceArea: "SE3", label: "E.ON Energidistribution AB Danderyd" },
  "EKG": { priceArea: "SE3", label: "E.ON Energidistribution AB Enk\u00f6ping" },
  "HLD": { priceArea: "SE4", label: "E.ON Energidistribution AB Halland" },
  "HAM": { priceArea: "SE2", label: "E.ON Energidistribution AB Hammarstrand" },
  "HRS": { priceArea: "SE2", label: "E.ON Energidistribution AB Harrsele region" },
  "HJR": { priceArea: "SE3", label: "E.ON Energidistribution AB Hj\u00e4lmaren Region" },
  "KBR": { priceArea: "SE2", label: "E.ON Energidistribution AB Korsselbr\u00e4nna region" },
  "KRF": { priceArea: "SE2", label: "E.ON Energidistribution AB Kramfors" },
  "KBA": { priceArea: "SE3", label: "E.ON Energidistribution AB Kungsbacka" },
  "LJV": { priceArea: "SE2", label: "E.ON Energidistribution AB Ljungan \u00d6vre region" },
  "LYC": { priceArea: "SE2", label: "E.ON Energidistribution AB Lycksele region" },
  "MMO": { priceArea: "SE4", label: "E.ON Energidistribution AB Malm\u00f6-Burl\u00f6v" },
  "MEL": { priceArea: "SE2", label: "E.ON Energidistribution AB Medelpad Lokal" },
  "NRL": { priceArea: "SE3", label: "E.ON Energidistribution AB Nerike Lokal" },
  "NSF": { priceArea: "SE3", label: "E.ON Energidistribution AB Nissafors" },
  "NRR": { priceArea: "SE3", label: "E.ON Energidistribution AB Nora Region" },
  "NKR": { priceArea: "SE3", label: "E.ON Energidistribution AB Norrk\u00f6ping Region" },
  "SKL": { priceArea: "SE4", label: "E.ON Energidistribution AB Sk\u00e5ne Landsbygd" },
  "SKV": { priceArea: "SE4", label: "E.ON Energidistribution AB Sk\u00e5ne V\u00e4stra Lokaln\u00e4t" },
  "SMN": { priceArea: "SE3", label: "E.ON Energidistribution AB Sm\u00e5land Norra lokaln\u00e4t" },
  "SML": { priceArea: "SE3", label: "E.ON Energidistribution AB Sm\u00e5land region" },
  "SMS": { priceArea: "SE4", label: "E.ON Energidistribution AB Sm\u00e5land S\u00f6dra" },
  "SUR": { priceArea: "SE2", label: "E.ON Energidistribution AB Sundsvall region" },
  "SYD": { priceArea: "SE4", label: "E.ON Energidistribution AB Sydsvenska region" },
  "UPS": { priceArea: "SE3", label: "E.ON Energidistribution AB Uppland S\u00f6dra" },
  "ALL": { priceArea: "SE2", label: "E.ON Energidistribution AB \u00c5dalen Lokal" },
  "ADL": { priceArea: "SE2", label: "E.ON Energidistribution AB \u00c5dalen region" },
  "AKB": { priceArea: "SE3", label: "E.ON Energidistribution AB \u00c5kersberga" },
  "OLD": { priceArea: "SE4", label: "E.ON Energidistribution AB \u00d6land" },
  "OGO": { priceArea: "SE3", label: "E.ON Energidistribution AB \u00d6stra G\u00f6taland" },
  "ESJ": { priceArea: "SE3", label: "Eksj\u00f6 Eln\u00e4t AB Eksj\u00f6" },
  "BEV": { priceArea: "SE2", label: "Ellevio AB Bergvik region" },
  "NBL": { priceArea: "SE3", label: "Ellevio AB Bohusl\u00e4n Norra" },
  "DAL": { priceArea: "SE3", label: "Ellevio AB Dalarna region" },
  "EBN": { priceArea: "SE2", label: "Ellevio AB Edsbyn" },
  "EKO": { priceArea: "SE3", label: "Ellevio AB Eker\u00f6arna" },
  "FBA": { priceArea: "SE3", label: "Ellevio AB Forsbacka \u00d6vre" },
  "FLS": { priceArea: "SE2", label: "Ellevio AB F\u00e5gelsj\u00f6 Region" },
  "GRV": { priceArea: "SE2", label: "Ellevio AB Gr\u00f6nviken Region" },
  "GBN": { priceArea: "SE3", label: "Ellevio AB Gullsp\u00e5ngsbygden" },
  "NHA": { priceArea: "SE3", label: "Ellevio AB Halland Norra" },
  "HMM": { priceArea: "SE3", label: "Ellevio AB Hammar\u00f6" },
  "HMR": { priceArea: "SE2", label: "Ellevio AB Hamra" },
  "HDV": { priceArea: "SE2", label: "Ellevio AB Hudiksvall" },
  "HAL": { priceArea: "SE2", label: "Ellevio AB H\u00e4lsingland" },
  "HAR": { priceArea: "SE2", label: "Ellevio AB H\u00e4lsingland Region" },
  "HJD": { priceArea: "SE2", label: "Ellevio AB H\u00e4rjedalen region" },
  "JDA": { priceArea: "SE3", label: "Ellevio AB J\u00e4rva-Danderyd" },
  "KEM": { priceArea: "SE2", label: "Ellevio AB Kema Nord region" },
  "KOB": { priceArea: "SE3", label: "Ellevio AB Kopparbergsbyggden" },
  "KUB": { priceArea: "SE3", label: "Ellevio AB Kungsbacka region" },
  "LDG": { priceArea: "SE3", label: "Ellevio AB Liding\u00f6" },
  "LHD": { priceArea: "SE2", label: "Ellevio AB Lillh\u00e4rdal Region" },
  "MOR": { priceArea: "SE3", label: "Ellevio AB Mora-Orsa" },
  "NHN": { priceArea: "SE3", label: "Ellevio AB Nyn\u00e4shamn" },
  "OBO": { priceArea: "SE2", label: "Ellevio AB Ockelbo" },
  "ORT": { priceArea: "SE3", label: "Ellevio AB Orust-Tj\u00f6rn" },
  "STH": { priceArea: "SE3", label: "Ellevio AB Stockholm" },
  "STO": { priceArea: "SE3", label: "Ellevio AB Stockholm Region" },
  "TRJ": { priceArea: "SE3", label: "Ellevio AB Treje" },
  "TRS": { priceArea: "SE3", label: "Ellevio AB Tr\u00e4ngslet" },
  "TBY": { priceArea: "SE3", label: "Ellevio AB T\u00e4by" },
  "VAT": { priceArea: "SE3", label: "Ellevio AB Vallentuna" },
  "VNB": { priceArea: "SE3", label: "Ellevio AB Vansbro" },
  "VLB": { priceArea: "SE3", label: "Ellevio AB V\u00e5lberg-Segerstad" },
  "VAL": { priceArea: "SE3", label: "Ellevio AB V\u00e4rmland" },
  "VML": { priceArea: "SE3", label: "Ellevio AB V\u00e4rmland region" },
  "AVD": { priceArea: "SE3", label: "Ellevio AB \u00c4lvdalen" },
  "OCK": { priceArea: "SE3", label: "Ellevio AB \u00d6cker\u00f6" },
  "EBA": { priceArea: "SE4", label: "Emmaboda Eln\u00e4t AB Emmaboda" },
  "ESK": { priceArea: "SE3", label: "Eskilstuna Energi och Milj\u00f6 Eln\u00e4t AB Eskilstuna" },
  "SBV": { priceArea: "SE3", label: "Eskilstuna Energi och Milj\u00f6 Eln\u00e4t AB Svalboviken" },
  "FBN": { priceArea: "SE3", label: "Falbygdens Energi N\u00e4t AB Falbygden" },
  "FBG": { priceArea: "SE4", label: "Falkenberg Energi AB Falkenberg" },
  "FLN": { priceArea: "SE3", label: "Falu Eln\u00e4t AB Falun" },
  "FLO": { priceArea: "SE3", label: "Falu Eln\u00e4t AB Falun nordost" },
  "FPD": { priceArea: "SE3", label: "Filipstad Energin\u00e4t AB Filipstad" },
  "JUV": { priceArea: "SE2", label: "Fortum Sverige AB Juveln" },
  "JPS": { priceArea: "SE2", label: "Fortum Sverige AB J\u00e4rpstr\u00f6mmen region" },
  "KRG": { priceArea: "SE2", label: "Fortum Sverige AB Kr\u00e5ngede region" },
  "LEV": { priceArea: "SE2", label: "Fortum Sverige AB Linnvasselv" },
  "LAA": { priceArea: "SE2", label: "Fortum Sverige AB L\u00e5ng\u00e5" },
  "MRR": { priceArea: "SE2", label: "Fortum Sverige AB M\u00f6rsil region" },
  "GBT": { priceArea: "SE2", label: "Gabrielsberget Net AB Gabrielsberget" },
  "GIV": { priceArea: "SE3", label: "Gislaved Energi Eln\u00e4t AB Gislaved" },
  "GTL": { priceArea: "SE3", label: "Gotlands Eln\u00e4t AB Gotland" },
  "GTP": { priceArea: "SE3", label: "Gr\u00e4storp Energi ek f\u00f6r Gr\u00e4storp" },
  "FOB": { priceArea: "SE3", label: "G\u00e4vle Energi AB Forsbacka" },
  "GVL": { priceArea: "SE3", label: "G\u00e4vle Energi AB G\u00e4vle" },
  "HDS": { priceArea: "SE3", label: "G\u00e4vle Energi AB Hedesunda" },
  "GBG": { priceArea: "SE3", label: "G\u00f6teborg Energi N\u00e4t AB G\u00f6teborg" },
  "KKB": { priceArea: "SE3", label: "G\u00f6tene Elf\u00f6rening Kinnekullebygden" },
  "HBO": { priceArea: "SE3", label: "Habo Kraft AB Habo" },
  "HVI": { priceArea: "SE3", label: "Hallstaviks Elverk ek f\u00f6r Hallstavik" },
  "HMD": { priceArea: "SE4", label: "Halmstads Energi och Milj\u00f6 N\u00e4t AB Halmstad" },
  "HVN": { priceArea: "SE2", label: "Havsn\u00e4s Eln\u00e4t AB Havsn\u00e4s" },
  "HMH": { priceArea: "SE3", label: "Hedemora Energi AB Hedemorahyttorna" },
  "HLJ": { priceArea: "SE3", label: "Herrljunga Elektriska AB Herrljunga" },
  "HJO": { priceArea: "SE3", label: "Hjo Energi AB Hjo" },
  "HJM": { priceArea: "SE3", label: "Hj\u00e4rtums Elf\u00f6rening ek f\u00f6r Hj\u00e4rtum" },
  "HOF": { priceArea: "SE3", label: "Hofors Elverk AB Hofors" },
  "TOR": { priceArea: "SE3", label: "Hofors Elverk AB Tors\u00e5ker" },
  "VIK": { priceArea: "SE3", label: "Holmen Energi Eln\u00e4t Varsvik" },
  "HJN": { priceArea: "SE2", label: "H\u00e4rje\u00e5ns N\u00e4t AB H\u00e4rje\u00e5n" },
  "ANE": { priceArea: "SE2", label: "H\u00e4rje\u00e5ns N\u00e4t AB \u00c5nge" },
  "HSD": { priceArea: "SE2", label: "H\u00e4rn\u00f6sand Eln\u00e4t AB H\u00e4rn\u00f6sand" },
  "HRA": { priceArea: "SE3", label: "H\u00e4rryda Energi AB H\u00e4rryda" },
  "HOG": { priceArea: "SE4", label: "H\u00f6gan\u00e4s Energi AB H\u00f6gan\u00e4s" },
  "JUJ": { priceArea: "SE1", label: "Jukkasj\u00e4rvi Sockens Belysningsf\u00f6rening Jukkasj\u00e4rvi" },
  "JMT": { priceArea: "SE2", label: "J\u00e4mtkraft Eln\u00e4t AB J\u00e4mtland region" },
  "JML": { priceArea: "SE2", label: "J\u00e4mtkraft Eln\u00e4t AB J\u00e4mtlandsbygden" },
  "LAN": { priceArea: "SE2", label: "J\u00e4mtkraft Eln\u00e4t AB L\u00e4nsterh\u00f6jden" },
  "MAS": { priceArea: "SE2", label: "J\u00e4mtkraft Eln\u00e4t AB Midskog-\u00c5sk\u00e4len" },
  "JNK": { priceArea: "SE3", label: "J\u00f6nk\u00f6ping Energi N\u00e4t AB J\u00f6nk\u00f6ping" },
  "KMR": { priceArea: "SE4", label: "Kalmar Energi Eln\u00e4t AB Kalmar" },
  "KBG": { priceArea: "SE3", label: "Karlsborgs Energi AB Karlsborg" },
  "KHN": { priceArea: "SE4", label: "Karlshamn Energi Karlshamn" },
  "KSA": { priceArea: "SE3", label: "Karlskoga Eln\u00e4t AB Karlskoga" },
  "KST": { priceArea: "SE3", label: "Karlstads El- och Stadsn\u00e4t Karlstad" },
  "ALD": { priceArea: "SE3", label: "Kraftn\u00e4t \u00c5land (SE) \u00c5land" },
  "BJK": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Bj\u00f6rnekulla" },
  "HLB": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Hallabro" },
  "HOR": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB H\u00f6\u00f6r" },
  "KPN": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Klippan" },
  "LMA": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Lomma" },
  "LUN": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Lund" },
  "RSJ": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Ringsj\u00f6" },
  "TOS": { priceArea: "SE4", label: "Kraftringen N\u00e4t AB Tors\u00e5s" },
  "KRH": { priceArea: "SE3", label: "Kristinehamns Eln\u00e4t AB Kristinehamn" },
  "KUV": { priceArea: "SE3", label: "Kung\u00e4lv Energi AB Kung\u00e4lv" },
  "KFN": { priceArea: "SE2", label: "Kvarnforsen N\u00e4t AB Kvarnforsen" },
  "KVM": { priceArea: "SE3", label: "Kv\u00e4numbygdens Energi ek. f\u00f6r Kv\u00e4num" },
  "LKA": { priceArea: "SE4", label: "Landskrona Energi AB Landskrona" },
  "LEH": { priceArea: "SE1", label: "Lehtirova N\u00e4t AB Lehtirova" },
  "LRM": { priceArea: "SE3", label: "Lerum Energi AB Lerum" },
  "LYS": { priceArea: "SE3", label: "LEVA i Lysekil AB Lysekil" },
  "LDK": { priceArea: "SE3", label: "Lidk\u00f6ping Eln\u00e4t Lidk\u00f6ping" },
  "LDB": { priceArea: "SE3", label: "Linde Energi AB Lindesberg" },
  "NKL": { priceArea: "SE3", label: "Linde Energi AB N\u00e4rkes Kil" },
  "LBY": { priceArea: "SE4", label: "Ljungby Energin\u00e4t AB Ljungby" },
  "LJD": { priceArea: "SE2", label: "Ljusdal Eln\u00e4t AB Ljusdal" },
  "KLK": { priceArea: "SE1", label: "LKAB N\u00e4t AB Kiruna LKAB" },
  "MBT": { priceArea: "SE1", label: "LKAB N\u00e4t AB Malmberget LKAB" },
  "LUL": { priceArea: "SE1", label: "Lule\u00e5 Energi Eln\u00e4t AB Lule\u00e5" },
  "MLG": { priceArea: "SE3", label: "Malungs Eln\u00e4t AB Malung" },
  "TYS": { priceArea: "SE3", label: "Malungs Eln\u00e4t AB Tyngsj\u00f6-Finnmarken" },
  "URM": { priceArea: "SE3", label: "Malungs Eln\u00e4t AB Uppr\u00e4mmen" },
  "MBN": { priceArea: "SE1", label: "Markbygden Net AB Markbygden" },
  "DBB": { priceArea: "SE1", label: "Markbygden Net V\u00e4st AB Dubblabergen" },
  "SNM": { priceArea: "SE4", label: "Mellerst Sk\u00e5nes Kraft, ek f\u00f6r Sk\u00e5ne Mellersta" },
  "MBY": { priceArea: "SE3", label: "Mj\u00f6lby Kraftn\u00e4t AB Mj\u00f6lby" },
  "MUL": { priceArea: "SE2", label: "Mullbergs Eln\u00e4t AB Mullberget" },
  "AOS": { priceArea: "SE3", label: "M\u00e4larenergi AB Aros" },
  "TLB": { priceArea: "SE3", label: "M\u00e4larenergi Eln\u00e4t AB Tillberga" },
  "VLS": { priceArea: "SE3", label: "M\u00e4larenergi Eln\u00e4t AB V\u00e4stmanland S\u00f6dra" },
  "MDL": { priceArea: "SE3", label: "M\u00f6lndal Energi N\u00e4t AB M\u00f6lndal" },
  "JRA": { priceArea: "SE3", label: "Nacka Energi AB J\u00e4rla" },
  "SSJ": { priceArea: "SE3", label: "Njudung Energi S\u00e4vsj\u00f6 AB S\u00e4vsj\u00f6" },
  "VTL": { priceArea: "SE3", label: "Njudung Vetlanda Eln\u00e4t AB Vetlanda" },
  "NTE": { priceArea: "SE3", label: "Norrt\u00e4lje Energi AB Norrt\u00e4lje" },
  "NSB": { priceArea: "SE3", label: "Nossebroortens Energi Ekonomisk F\u00f6rening Nossebro" },
  "NBR": { priceArea: "SE4", label: "Nybro Eln\u00e4t AB Nybro" },
  "SBK": { priceArea: "SE3", label: "N\u00e4ck\u00e5ns Eln\u00e4t AB Syssleb\u00e4ck" },
  "NSO": { priceArea: "SE3", label: "N\u00e4ssj\u00f6 Aff\u00e4rsverk Eln\u00e4t AB N\u00e4ssj\u00f6" },
  "OLS": { priceArea: "SE4", label: "Olofstr\u00f6ms Kraft N\u00e4t AB Olofstr\u00f6m" },
  "OSD": { priceArea: "SE4", label: "Olser\u00f6ds Elektriska Distributionsf\u00f6rening Olser\u00f6d" },
  "OHN": { priceArea: "SE4", label: "Oskarshamn Energi N\u00e4t AB Oskarshamn t\u00e4tort" },
  "HFB": { priceArea: "SE3", label: "Ovako Sweden AB Hofors Bruk" },
  "OXD": { priceArea: "SE3", label: "Oxel\u00f6 Energi AB Oxel\u00f6sund" },
  "PTE": { priceArea: "SE3", label: "Partille Energi N\u00e4t AB Partille" },
  "RBY": { priceArea: "SE4", label: "Ronneby Milj\u00f6 & Teknik AB Ronneby" },
  "RBF": { priceArea: "SE3", label: "R\u00f6bergsfj\u00e4llet N\u00e4t AB R\u00f6bergsfj\u00e4llet" },
  "ROY": { priceArea: "SE4", label: "R\u00f6deby Elverk ek f\u00f6r R\u00f6deby" },
  "HBY": { priceArea: "SE3", label: "Sala-Heby Energi Eln\u00e4t AB Heby" },
  "SAH": { priceArea: "SE3", label: "Sala-Heby Energi Eln\u00e4t AB Sala-Hyttan" },
  "VBK": { priceArea: "SE3", label: "Sala-Heby Energi Eln\u00e4t AB V\u00e4sterbykil" },
  "SHT": { priceArea: "SE3", label: "Sandhult-Sandared Elektriska ek f\u00f6r Sandhult-Sandared" },
  "SDV": { priceArea: "SE3", label: "Sandviken Energi Eln\u00e4t AB Sandviken" },
  "OFB": { priceArea: "SE3", label: "Sandviken Energi Eln\u00e4t AB \u00d6sterf\u00e4rnebo" },
  "SGS": { priceArea: "SE3", label: "SEVAB N\u00e4t AB Str\u00e4ngn\u00e4s T\u00e4tort" },
  "SID": { priceArea: "SE2", label: "Sidensj\u00f6 Vindkraft Eln\u00e4t AB Sidensj\u00f6" },
  "SJN": { priceArea: "SE1", label: "Sjisjka N\u00e4t AB Sjisjka" },
  "SJO": { priceArea: "SE3", label: "Sjogerstads Elektriska Distributionsf\u00f6rening Sjogerstad" },
  "SJB": { priceArea: "SE4", label: "Sj\u00f6bo Eln\u00e4t AB Sj\u00f6bo" },
  "SKA": { priceArea: "SE3", label: "Skara Energi AB Skara" },
  "BYG": { priceArea: "SE2", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Bygde\u00e5-Robertsfors" },
  "LYX": { priceArea: "SE2", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Lyckselebygden" },
  "SKT": { priceArea: "SE1", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Skellefte\u00e5" },
  "SKF": { priceArea: "SE1", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Skellefte\u00e5 region" },
  "SOL": { priceArea: "SE2", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Solberg region" },
  "VDN": { priceArea: "SE2", label: "Skellefte\u00e5 Kraft Eln\u00e4t AB Vindeln" },
  "SKP": { priceArea: "SE4", label: "Skurups Elverk AB Skurup" },
  "SBR": { priceArea: "SE3", label: "Skyllbergs Bruk AB Skyllbergs Bruk" },
  "SKN": { priceArea: "SE4", label: "Sk\u00e5nska Energi N\u00e4t AB Sk\u00e5nska" },
  "SKD": { priceArea: "SE3", label: "Sk\u00f6vde Energi Eln\u00e4t AB Sk\u00f6vde" },
  "SMB": { priceArea: "SE3", label: "Smedjebacken Energi N\u00e4t AB Smedjebacken" },
  "SOT": { priceArea: "SE3", label: "Sollentuna Energi AB Sollentuna" },
  "SFP": { priceArea: "SE4", label: "Staffanstorps Energi AB Staffanstorp" },
  "STF": { priceArea: "SE2", label: "Stensj\u00f6n Kraft AB Stensj\u00f6fallet region" },
  "SRF": { priceArea: "SE3", label: "Sturefors Eldistribution AB Sturefors" },
  "SUV": { priceArea: "SE2", label: "Sundsvall Eln\u00e4t AB Sundsvall t\u00e4tort" },
  "ARN": { priceArea: "SE3", label: "Swedavia Energi AB Stockholm-Arlanda" },
  "AJG": { priceArea: "SE2", label: "Svenska kraftn\u00e4t Ajaure-Grundfors" },
  "KON": { priceArea: "SE3", label: "Svenska kraftn\u00e4t Konti-Skan st" },
  "PLT": { priceArea: "SE4", label: "Svenska kraftn\u00e4t NordBalt" },
  "POL": { priceArea: "SE4", label: "Svenska kraftn\u00e4t Polen" },
  "ST1": { priceArea: "SE1", label: "Svenska kraftn\u00e4t Stamn\u00e4t Snittomr\u00e5de 1" },
  "ST2": { priceArea: "SE2", label: "Svenska kraftn\u00e4t Stamn\u00e4t Snittomr\u00e5de 2" },
  "ST3": { priceArea: "SE3", label: "Svenska kraftn\u00e4t Stamn\u00e4t Snittomr\u00e5de 3" },
  "ST4": { priceArea: "SE4", label: "Svenska kraftn\u00e4t Stamn\u00e4t Snittomr\u00e5de 4" },
  "SWP": { priceArea: "SE4", label: "Svenska kraftn\u00e4t SwePollink" },
  "TYV": { priceArea: "SE4", label: "Svenska kraftn\u00e4t Tyskland v\u00e4st" },
  "SHN": { priceArea: "SE2", label: "S\u00f6derhamn Eln\u00e4t AB S\u00f6derhamn" },
  "LHM": { priceArea: "SE4", label: "S\u00f6dra Hallands Kraft ekonomisk f\u00f6rening Laholm" },
  "SBG": { priceArea: "SE4", label: "S\u00f6lvesborg Energi och Vatten AB S\u00f6lvesborg" },
  "SBL": { priceArea: "SE3", label: "S\u00f6rbylunds Eln\u00e4t AB S\u00f6rbylund" },
  "KHB": { priceArea: "SE3", label: "Tekniska verken i Katrineholm N\u00e4t AB Katrineholmsbygden" },
  "LNK": { priceArea: "SE3", label: "Tekniska verken Link\u00f6ping N\u00e4t AB Link\u00f6ping" },
  "SDT": { priceArea: "SE3", label: "Telge N\u00e4t AB S\u00f6dert\u00e4lje" },
  "TIB": { priceArea: "SE3", label: "Tibro Energi AB Tibro" },
  "THM": { priceArea: "SE3", label: "Tidaholms Eln\u00e4t AB Tidaholm" },
  "TNS": { priceArea: "SE3", label: "Tran\u00e5s Energi Eln\u00e4t AB Tran\u00e5s" },
  "TBG": { priceArea: "SE4", label: "Trelleborgs kommun Trelleborg" },
  "TRH": { priceArea: "SE3", label: "Trollh\u00e4ttan Energi Eln\u00e4t AB Trollh\u00e4ttan" },
  "TRE": { priceArea: "SE1", label: "T\u00f6re Energi ek f\u00f6r T\u00f6re" },
  "UVA": { priceArea: "SE3", label: "Uddevalla Energi Eln\u00e4t AB Uddevalla" },
  "UHN": { priceArea: "SE3", label: "Ulricehamns Energi AB Ulricehamn" },
  "UMA": { priceArea: "SE2", label: "Ume\u00e5 Energi Eln\u00e4t AB Ume\u00e5" },
  "UME": { priceArea: "SE2", label: "Ume\u00e5 Energi Eln\u00e4t AB Ume\u00e5 region" },
  "BJL": { priceArea: "SE3", label: "Upplands Energi Bj\u00f6rklinge" },
  "VGD": { priceArea: "SE3", label: "Vaggeryds Elverk Vaggeryd" },
  "VAB": { priceArea: "SE3", label: "Vallebygdens Energi ek f\u00f6r Vallebygden" },
  "VAR": { priceArea: "SE3", label: "Vara Energi ek.f\u00f6r Vara" },
  "VBG": { priceArea: "SE3", label: "Varberg Energi AB Varberg" },
  "VBN": { priceArea: "SE3", label: "Varbergsortens Elkraft ek f\u00f6r Varbergsorten Norra" },
  "VBS": { priceArea: "SE3", label: "Varbergsortens Elkraft ek f\u00f6r Varbergsorten S\u00f6dra" },
  "ARD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Ardala" },
  "AJB": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Arvidsjaurbygden" },
  "AVE": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Avesta" },
  "AVR": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Avesta region" },
  "BGS": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Bergslagen region" },
  "BGO": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Bergslagen \u00d6stra" },
  "BLT": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Bj\u00f6rnlandet" },
  "DAD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Dalsland med omnejd" },
  "DRV": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Drefviken" },
  "FSB": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Finsp\u00e5ngsbygden" },
  "FLE": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Flen" },
  "FMD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Fr\u00e4mmestad" },
  "GAM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Gammelstilla" },
  "GAB": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Garpenberg" },
  "GDB": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Gideobygden" },
  "GTA": { priceArea: "SE3", label: "Vattenfall Eldistribution AB G\u00f6ta" },
  "HDL": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Horndal" },
  "HDG": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Huddinge" },
  "HUV": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Huvudsta" },
  "ING": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Ingar\u00f6" },
  "KAB": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Kalixbygden" },
  "KND": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Kind" },
  "LGR": { priceArea: "SE4", label: "Vattenfall Eldistribution AB Lillgrund" },
  "LAO": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Lule\u00e4lven \u00d6vre" },
  "MAF": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Malmf\u00e4lten" },
  "MSD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Marstrand" },
  "VFM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Mellansverige region" },
  "MYN": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Myr\u00e5sen" },
  "NOB": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Norberg" },
  "VFN": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Norrbotten region" },
  "NYK": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Nyk\u00f6ping" },
  "NYD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Nyk\u00f6ping Landsbygd" },
  "RSK": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Roslagskusten" },
  "SIG": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Sigtuna" },
  "SHD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Sjuh\u00e4rad" },
  "SKR": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Skillingaryd" },
  "SLD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Sk\u00f6vde Landsbygd" },
  "SGD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Stenungsund" },
  "SYM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Sydm\u00e4laren" },
  "SFE": { priceArea: "SE3", label: "Vattenfall Eldistribution AB S\u00e4ffle" },
  "TNN": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Tornedalen Nedre" },
  "TDO": { priceArea: "SE1", label: "Vattenfall Eldistribution AB Tornedalen \u00d6vre" },
  "TUM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Tumba" },
  "TYR": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Tyres\u00f6" },
  "UMD": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Ume\u00e4lven Nedre" },
  "UMN": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Ume\u00e4lven region" },
  "UMO": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Ume\u00e4lven \u00d6vre" },
  "UPN": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Uppland Norra" },
  "UPV": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Uppland V\u00e4stra" },
  "UPO": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Uppland \u00d6stra" },
  "UPP": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Uppsala" },
  "VAG": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Vagnh\u00e4rad" },
  "VDM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Vedum" },
  "VMA": { priceArea: "SE2", label: "Vattenfall Eldistribution AB Vilhelmina" },
  "VIG": { priceArea: "SE3", label: "Vattenfall Eldistribution AB Ving\u00e5kersbygden" },
  "VMD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB V\u00e4rmd\u00f6" },
  "VRO": { priceArea: "SE3", label: "Vattenfall Eldistribution AB V\u00e4r\u00f6 region" },
  "VAD": { priceArea: "SE3", label: "Vattenfall Eldistribution AB V\u00e4stanhede" },
  "VFV": { priceArea: "SE3", label: "Vattenfall Eldistribution AB V\u00e4stsverige region" },
  "VAN": { priceArea: "SE3", label: "Vattenfall Eldistribution AB V\u00e4tterbygden" },
  "AML": { priceArea: "SE3", label: "Vattenfall Eldistribution AB \u00c5m\u00e5l" },
  "ANN": { priceArea: "SE2", label: "Vattenfall Eldistribution AB \u00c5nge region" },
  "AMN": { priceArea: "SE2", label: "Vattenfall Eldistribution AB \u00c5ngerman\u00e4lven region" },
  "ANG": { priceArea: "SE3", label: "Vattenfall Eldistribution AB \u00c5rj\u00e4ng" },
  "ABB": { priceArea: "SE1", label: "Vattenfall Eldistribution AB \u00c4lvsbybygden" },
  "OHM": { priceArea: "SE3", label: "Vattenfall Eldistribution AB \u00d6sthammar" },
  "VFO": { priceArea: "SE3", label: "Vattenfall Eldistribution AB \u00d6stsverige region" },
  "JKE": { priceArea: "SE2", label: "Vattenfall Kraftg\u00e5rden AB J\u00e4rkvissle" },
  "NFO": { priceArea: "SE2", label: "Vattenfall Kraftg\u00e5rden AB N\u00e4mforsen region" },
  "STU": { priceArea: "SE2", label: "Vattenfall Kraftg\u00e5rden AB Stugun region" },
  "VGF": { priceArea: "SE3", label: "Viggafors Elektriska Andelsf\u00f6rening Upa Viggafors" },
  "VBY": { priceArea: "SE3", label: "Vimmerby Energi N\u00e4t AB Vimmerby" },
  "GLG": { priceArea: "SE3", label: "Vindpark V\u00e4nern Drift AB G\u00e4sslingegrund" },
  "MAI": { priceArea: "SE3", label: "V\u00e4nerEnergi AB Mariestad" },
  "TBA": { priceArea: "SE3", label: "V\u00e4nerEnergi AB T\u00f6reboda" },
  "VMO": { priceArea: "SE4", label: "V\u00e4rnamo Eln\u00e4t AB V\u00e4rnamo" },
  "FGA": { priceArea: "SE3", label: "V\u00e4sterbergslagens Eln\u00e4t AB Fagersta" },
  "VAS": { priceArea: "SE3", label: "V\u00e4sterbergslagens Eln\u00e4t AB V\u00e4stanfors" },
  "VBL": { priceArea: "SE3", label: "V\u00e4sterbergslagens Eln\u00e4t AB V\u00e4sterbergslagen" },
  "VBR": { priceArea: "SE3", label: "V\u00e4sterbergslagens Eln\u00e4t AB V\u00e4sterbergslagen Regionaln\u00e4t" },
  "VVI": { priceArea: "SE3", label: "V\u00e4sterviks Kraft Eln\u00e4t AB V\u00e4stervik" },
  "ORV": { priceArea: "SE3", label: "V\u00e4stra Orusts Energitj\u00e4nst ek. f\u00f6r. Orust V\u00e4stra" },
  "VXO": { priceArea: "SE4", label: "V\u00e4xj\u00f6 Energi Eln\u00e4t AB V\u00e4xj\u00f6" },
  "YST": { priceArea: "SE4", label: "Ystad Energi AB Ystad" },
  "ALM": { priceArea: "SE4", label: "\u00c5lem Energi AB \u00c5lem" },
  "ARS": { priceArea: "SE3", label: "\u00c5rsunda Kraft-o Belysningsf\u00f6rening Upa \u00c5rsunda" },
  "ASL": { priceArea: "SE2", label: "\u00c5sele Eln\u00e4t AB \u00c5sele" },
  "ASK": { priceArea: "SE2", label: "\u00c5sk\u00e4len Vindkraft Eln\u00e4t AB \u00c5sk\u00e4len" },
  "HBG": { priceArea: "SE4", label: "\u00d6resundskraft AB Helsingborg" },
  "MRP": { priceArea: "SE4", label: "\u00d6resundskraft AB M\u00f6rarp" },
  "NVS": { priceArea: "SE4", label: "\u00d6resundskraft AB Nordv\u00e4stra Sk\u00e5ne" },
  "SKH": { priceArea: "SE4", label: "\u00d6resundskraft AB Sk\u00e5ne-Halland region" },
  "AHB": { priceArea: "SE4", label: "\u00d6resundskraft AB \u00c4ngelholmsbygden" },
  "SIH": { priceArea: "SE4", label: "\u00d6sterlens Kraft AB Simrishamn" },
  "OLN": { priceArea: "SE4", label: "\u00d6sterlens Kraft AB \u00d6sterlen" },
  "DAP": { priceArea: "SE3", label: "\u00d6stra Kinds Elkraft Dalstorp" },
  "TDN": { priceArea: "SE1", label: "\u00d6vertorne\u00e5 Energi AB Tornedalen" },
  "DOF": { priceArea: "SE2", label: "\u00d6vik Energi N\u00e4t AB Domsj\u00f6 Fabriksomr\u00e5de" },
  "OVK": { priceArea: "SE2", label: "\u00d6vik Energi N\u00e4t AB \u00d6rnsk\u00f6ldsvik" }
}

export function normalizeGridAreaCode(value: unknown): string | null {
  if (typeof value !== 'string' && typeof value !== 'number') return null
  const normalized = String(value).trim().toUpperCase()
  return /^[A-ZÅÄÖ0-9]{2,8}$/.test(normalized) ? normalized : null
}

export function getFallbackPriceAreaForGridArea(code: unknown): WebsiteGridAreaPriceAreaRow | null {
  const normalized = normalizeGridAreaCode(code)
  return normalized ? WEBSITE_GRID_AREA_PRICE_AREAS[normalized] ?? null : null
}
