export type StaffContext = {
  status: 'anonymous' | 'authenticated' | 'mfa_required' | 'password_change_required'
  csrf_token: string
  factors: Array<{ factor_reference: string; method: 'totp'; friendly_name: string | null }>
  staff: null | { staff_reference: string; display_name: string | null; organization_reference: string; is_platform_admin: boolean; permissions: string[]; capabilities: string[] }
}
export type StaffPage = { limit: number; returned: number; has_more: boolean; next_cursor: string | null }
export type StaffResponse<T> = { data: T; page?: StaffPage; request_id: string; correlation_id?: string; contract_schema_version: string }
export type StaffCustomer = { customer_reference: string; customer_number: string | null; customer_type: string | null; status: string | null; display_name: string | null; email: string | null; phone: string | null; created_at: string | null }
export type StaffCustomerDetail = StaffCustomer & { first_name: string | null; last_name: string | null; company_name: string | null; masked_personal_number: string | null; org_number: string | null; apartment_number: string | null; preferred_language: string | null; updated_at: string | null; moved_out_at: string | null; lifecycle_closed_at: string | null }
export type StaffContact = { contact_reference: string; type: string | null; name: string | null; email: string | null; phone: string | null; title: string | null; is_primary: boolean | null; created_at: string | null }
export type StaffAddress = { address_reference: string; type: string | null; street_1: string | null; street_2: string | null; postal_code: string | null; city: string | null; country: string | null; municipality: string | null; moved_in_at: string | null; moved_out_at: string | null; is_active: boolean | null; created_at: string | null }
export type StaffFacility = { facility_reference: string; site_name: string | null; facility_id: string | null; site_type: string | null; status: string | null; street: string | null; care_of: string | null; postal_code: string | null; city: string | null; country: string | null; grid_area_code: string | null; price_area_code: string | null; move_in_date: string | null; move_out_date: string | null; created_at: string | null; updated_at: string | null }
export type StaffAssignee = { staff_reference: string; display_name: string }
export type StaffCase = { case_reference: string; customer_reference: string; customer_number: string | null; customer_display_name: string | null; facility_reference: string | null; title: string; description: string | null; description_visibility: string; category: string | null; status: string; public_status: string; priority: string; channel: string | null; assigned_to: StaffAssignee | null; next_action: string | null; next_action_due_at: string | null; created_at: string; updated_at: string; resolved_at: string | null; closed_at: string | null }
export type StaffEntry = { entry_reference: string; case_reference: string; kind: string; visibility: 'internal' | 'customer'; author_type: 'customer' | 'staff' | 'system'; author: StaffAssignee | null; body: string | null; created_at: string | null; reply_kind?: 'message' | 'phone_summary'; status?: string | null; assignee_reference?: string | null }
export type StaffAttachment = { case_reference: string; attachment_reference: string; file_name: string; mime_type: string | null; byte_size: number; sha256: string; visibility: 'internal' | 'customer'; uploaded_by: 'staff' | 'customer'; scan_status: 'quarantined' | 'released' | 'rejected'; scan_reason: string | null; created_at: string }
