import type { SeoPageContent } from './content'

type LocationContent = Pick<SeoPageContent, 'sections' | 'faq' | 'related'>
type Section = SeoPageContent['sections'][number]

const localTopics: Record<string, { heading: string; body: string[]; question: string; answer: string; guide: string; guideLabel: string }> = {
  skane: { heading: 'Jämför orter i Skåne på samma områdesgrund', body: ['Malmö, Helsingborg, Lund och Landskrona behandlas här som anslutningar i SE4. När uppgifter för dessa orter avser samma intervall ska marknadspriset jämföras inom samma elområde.', 'En regional jämförelse behöver ändå skilja elhandeln från olika nätabonnemang och förbrukningsmönster. Kontrollera varje anläggning innan flera bostäder eller verksamheter summeras.'], question: 'Kan två hushåll i Skåne ha olika elkostnad trots samma elområde?', answer: 'Ja. Användning, avtalsmodell, avgifter och nätabonnemang kan skilja sig. SE4-priset är bara en del av underlaget.', guide: '/guider/elomraden-se1-se2-se3-se4', guideLabel: 'Förstå elområden' },
  landskrona: { heading: 'Jämför en egen bostad med ett gemensamt abonnemang', body: ['För en bostad i Landskrona behöver du först veta om elen mäts på ett eget abonnemang eller inom en gemensam lösning. Det påverkar vem som väljer elhandelsavtal.', 'Om en förening hanterar gemensam el bör du kontrollera hur avgifter fördelas innan du jämför med ett erbjudande för ett eget hushåll. Använd din faktiska anslutning som underlag.'], question: 'Kan jag teckna eget elavtal om föreningen har gemensam el?', answer: 'Kontrollera hur abonnemanget är ordnat. Vid gemensam anslutning är det normalt föreningen som väljer elhandlare för den anslutningen.', guide: '/elavtal/bostadsratt', guideLabel: 'Elavtal för bostadsrätt' },
  stockholm: { heading: 'Skilj lägenhetens hushållsel från uppvärmning', body: ['När du jämför för en lägenhet i Stockholm behöver du veta om värme och varmvatten ingår i boendet. Då är den egna förbrukningen ett annat underlag än för ett eluppvärmt hus.', 'Vid låg användning kan fasta elhandelsavgifter få stor betydelse. Kontrollera också om bostaden har en egen anslutning eller gemensam el innan du tecknar.'], question: 'Ska jag räkna med uppvärmning när jag jämför lägenhetens elavtal?', answer: 'Bara om uppvärmningen faktiskt ligger på den egna elmätaren. Kontrollera vad som ingår i boendekostnaden.', guide: '/elavtal/lagenhet', guideLabel: 'Elavtal för lägenhet' },
  goteborg: { heading: 'Använd hela året om huset har elvärme', body: ['För ett hus i Göteborg med elvärme eller värmepump kan vinteranvändningen påverka årsbudgeten. Jämför ett helt år i stället för att utgå från en enda varm månad.', 'Om uppvärmningen har ändrats behöver historiken justeras. Väg också in hur mycket av användningen som går att styra innan du jämför kvartspris och månadspris.'], question: 'Räcker en sommarmånad för att välja avtal till ett eluppvärmt hus?', answer: 'Den kan underskatta både årsförbrukning och vinterkostnad. Använd årshistorik och information om uppvärmningen.', guide: '/guider/varmepump-elforbrukning', guideLabel: 'Värmepumpens elförbrukning' },
  malmo: { heading: 'Kontrollera elen inför en flytt i Malmö', body: ['En flytt till en annan bostad i Malmö kan innebära en annan anslutning även om elområdet fortfarande är SE4. Kontrollera startdatum för både elhandel och nätabonnemang.', 'Hantera den tidigare adressen separat och spara bekräftelser. Ett nytt elhandelsavtal innebär inte att den gamla anslutningens avtal automatiskt är avslutade.'], question: 'Behöver jag kontrollera nätavtalet även vid flytt inom Malmö?', answer: 'Ja. Avtalet gäller en anläggning, inte bara en stad eller person. Kontrollera båda adresserna.', guide: '/elavtal/teckna-elavtal-vid-flytt', guideLabel: 'Teckna elavtal vid flytt' },
  helsingborg: { heading: 'Bedöm laddning med både energi och effekt', body: ['Om du laddar en elbil hemma i Helsingborg behöver du räkna med energin från nätet och inte bara batteriets ökning. Avtalsform och laddtid påverkar energikostnaden.', 'Kontrollera nätägarens tariff innan flera stora laster startas samtidigt. Ett lågt kvartpris i SE4 säger inte ensamt vad hela laddningen kostar.'], question: 'Är det alltid billigast att ladda när SE4-priset är lägst?', answer: 'Avtalets beräkning, laddförluster, andra avgifter och eventuell effektdel i nättariffen behöver också bedömas.', guide: '/guider/ladda-elbil-billigare', guideLabel: 'Ladda elbil billigare' },
  lund: { heading: 'Fasta avgifter vid låg årsförbrukning', body: ['För en bostad i Lund med låg hushållsförbrukning bör månadsavgiften räknas om till årskostnad. Den tas normalt även de månader då användningen är liten.', 'Ett lägre påslag ger en mindre besparing i kronor när antalet kWh är lågt. Jämför därför både fasta och rörliga kostnader på samma förbrukning, utan att anta ett visst behov utifrån orten.'], question: 'Kan månadsavgiften vara viktigare än påslaget?', answer: 'Vid låg förbrukning kan den få större betydelse. Räkna på den egna årsförbrukningen innan du jämför.', guide: '/elavtal/billigt-elavtal', guideLabel: 'Räkneexempel för billig el' },
  trelleborg: { heading: 'Bedöm en bostad som används säsongsvis', body: ['Om en bostad i Trelleborg bara används under delar av året behöver även tomma månader ingå i jämförelsen. Grundvärme, ventilation och fasta avgifter kan finnas kvar.', 'Att ändra elhandelsavtal är inte samma sak som att koppla från nätanslutningen. Kontrollera byggnadens behov och nätvillkoren innan du överväger en säsongslösning.'], question: 'Försvinner månadsavgiften när bostaden står tom?', answer: 'Inte normalt om avtalet fortsätter. Läs den fasta avgiftens villkor och bedöm hela året.', guide: '/elavtal/fritidshus', guideLabel: 'Elavtal för fritidshus' },
  kristianstad: { heading: 'Skilj verksamhetens pris från dess fakturabelopp', body: ['När en verksamhet i Kristianstad jämför elavtal behöver alla prisrader vara på samma momsgrund. Ett belopp utan moms kan inte jämföras direkt med ett hushållspris inklusive moms.', 'Använd verksamhetens förbrukningshistorik och kontrollera om flera anläggningar har olika avgifter. Summera inte enbart annonserade kWh-priser utan att läsa avtalsmodellerna.'], question: 'Kan företagspris utan moms jämföras direkt med konsumentpris?', answer: 'Nej. Gör om beloppen till samma momsgrund och kontrollera avgifter och beräkningsperiod.', guide: '/elavtal/foretag', guideLabel: 'Elavtal för företag' },
  uppsala: { heading: 'Ta fram underlag inför det första egna elavtalet', body: ['Inför inflyttning i en bostad i Uppsala bör du fråga om el ingår eller om egna avtal behövs. Kontrollera också tillträdesdatum och exakt bostadsadress.', 'Saknas förbrukningshistorik, bedöm flera scenarier efter boendeform och uppvärmning. Den tidigare boendes användning kan vara ett underlag men behöver inte motsvara din.'], question: 'Hur jämför jag om jag inte vet förbrukningen i nya bostaden?', answer: 'Fråga efter historik och jämför flera rimliga scenarier. Kontrollera vilka funktioner som ligger på den egna elmätaren.', guide: '/elavtal/hyresratt', guideLabel: 'Elavtal för hyresrätt' },
  vasteras: { heading: 'Jämför när ditt användningsmönster ändras', body: ['För ett hushåll i Västerås kan installation av laddbox eller värmepump ändra både mängden el och tidpunkten för användningen. Då kan ett äldre kostnadsexempel behöva räknas om.', 'Bedöm vilken användning som går att flytta utan att skapa stora samtidiga laster. Elhandelsmodell och nättariff behöver vägas in tillsammans.'], question: 'Behöver jag jämföra avtalet igen efter att jag skaffat elbil?', answer: 'Det är lämpligt när förbrukning och användningstid ändras. Använd den nya profilen i stället för ett gammalt schablonexempel.', guide: '/guider/styr-din-elanvandning', guideLabel: 'Styr elanvändningen' },
  orebro: { heading: 'Kontrollera rabatten över hela avtalsperioden', body: ['När du jämför ett erbjudande för en anläggning i Örebro behöver rabattens längd skiljas från bindningstiden. Det ordinarie priset kan gälla under en stor del av perioden.', 'Räkna både kampanjmånader och efterföljande månader på samma förbrukningsunderlag. Kontrollera även om rabatten gäller påslag eller en fast avgift.'], question: 'Är rabattperioden samma sak som bindningstiden?', answer: 'Inte nödvändigtvis. Kontrollera datumen var för sig och vad kostnaden blir efter kampanjen.', guide: '/guider/rabatter-pa-elavtal', guideLabel: 'Jämför rabatter' },
  linkoping: { heading: 'Följ upp fakturans prisdelar', body: ['För en anläggning i Linköping bör fakturan jämföras med det egna avtalets beräkning, inte enbart ett publicerat spotpris för SE3. Period och momsgrund behöver stämma.', 'Kontrollera om förbrukningen är uppmätt eller uppskattad och hur fasta avgifter redovisas. Samla avtalsbekräftelse och faktura om någon prisrad behöver förklaras.'], question: 'Varför är fakturans kWh-pris inte samma som områdespriset?', answer: 'Avtalsmodell och tillägg kan ge ett annat pris. Kontrollera också att uppgifterna avser samma period och momsgrund.', guide: '/guider/sa-laser-du-din-elfaktura', guideLabel: 'Läs elfakturan' },
  jonkoping: { heading: 'Kontrollera anslutningen före regional jämförelse', body: ['Denna guide använder SE3 som områdesunderlag för Jönköping. Vid jämförelse med anläggningar på andra orter ska varje anslutnings elområde kontrolleras; ett län eller en region är inte samma indelning som elområden.', 'Om du har både permanentbostad och fritidshus kan de ha olika prisunderlag och nätvillkor. Gör separata jämförelser innan du summerar hushållets kostnad.'], question: 'Kan jag använda samma elområde för alla mina fastigheter?', answer: 'Bara om anslutningarna faktiskt tillhör samma område. Kontrollera varje anläggning och använd rätt områdesuppgifter.', guide: '/guider/elomraden-se1-se2-se3-se4', guideLabel: 'Kontrollera elområden' },
  umea: { heading: 'Skilj SE2-data från ett allmänt nordligt pris', body: ['Guiden utgår från SE2 för Umeå. Ett pris för SE1 eller ett genomsnitt för norra Sverige behöver inte motsvara det underlag din anslutning använder.', 'Jämför samma intervall när du följer skillnader mellan områden. Kundens avgifter, användning och nätabonnemang behöver sedan bedömas separat.'], question: 'Kan jag använda SE1-priset bara för att Umeå ligger i norra Sverige?', answer: 'Nej. Utgå från anslutningens faktiska elområde; den här guiden använder SE2.', guide: '/elpriser/se2', guideLabel: 'Fördjupning om SE2' },
  lulea: { heading: 'Kontrollera vinterprofil och kostnader utöver SE1', body: ['Guiden använder SE1 för Luleå. För ett eluppvärmt hem kan hög vinterförbrukning ha betydelse även om vissa marknadsintervall är billiga.', 'Räkna inte bort fasta avgifter eller nätkostnader när du bedömer låga marknadspriser. Kontrollera även hur skatter redovisas i ditt eget fakturaunderlag.'], question: 'Betyder ett lågt SE1-pris att hela vinterfakturan blir låg?', answer: 'Nej. Förbrukning, avtalsavgifter, nätkostnader och skatter påverkar totalen även när områdespriset är lågt.', guide: '/elpriser/elpris-vinter', guideLabel: 'Förstå vinterkostnaden' },
}

const locations = [
  { slug: 'skane', name: 'Skåne', area: 'SE4' },
  { slug: 'landskrona', name: 'Landskrona', area: 'SE4' },
  { slug: 'stockholm', name: 'Stockholm', area: 'SE3' },
  { slug: 'goteborg', name: 'Göteborg', area: 'SE3' },
  { slug: 'malmo', name: 'Malmö', area: 'SE4' },
  { slug: 'helsingborg', name: 'Helsingborg', area: 'SE4' },
  { slug: 'lund', name: 'Lund', area: 'SE4' },
  { slug: 'trelleborg', name: 'Trelleborg', area: 'SE4' },
  { slug: 'kristianstad', name: 'Kristianstad', area: 'SE4' },
  { slug: 'uppsala', name: 'Uppsala', area: 'SE3' },
  { slug: 'vasteras', name: 'Västerås', area: 'SE3' },
  { slug: 'orebro', name: 'Örebro', area: 'SE3' },
  { slug: 'linkoping', name: 'Linköping', area: 'SE3' },
  { slug: 'jonkoping', name: 'Jönköping', area: 'SE3' },
  { slug: 'umea', name: 'Umeå', area: 'SE2' },
  { slug: 'lulea', name: 'Luleå', area: 'SE1' },
]

export const locationContent: Record<string, LocationContent> = Object.fromEntries(locations.map(({ slug, name, area }) => {
  const topic = localTopics[slug]
  const sections: Section[] = [
    { title: `Hitta aktuella uppgifter för ${area}`, body: [`Den här guiden använder ${area} som elområde för ${name}. För aktuella prisuppgifter, öppna sidan Elpris idag och välj underlaget för ${area}. Kontrollera datum, intervall och momsgrund innan du jämför.`, `${name} har inte ett eget separat börsspotpris inom ${area}. Den här sidan är en områdes- och kostnadsguide, inte en egen lokal pristabell. Kontrollera alltid den faktiska anläggningen om områdestillhörigheten är osäker.`] },
    { title: topic.heading, body: topic.body },
  ]
  return [`/elpriser/${slug}`, {
    sections,
    faq: [{ question: topic.question, answer: topic.answer }],
    related: [
      { label: 'Elpris idag', href: '/elpriser/elpris-idag', description: `Öppna de befintliga prisuppgifterna och kontrollera ${area}.` },
      { label: `Elpris ${area}`, href: `/elpriser/${area.toLowerCase()}`, description: 'Förstå områdespris och kundkostnad.' },
      { label: topic.guideLabel, href: topic.guide, description: 'Fördjupa frågan i denna guide.' },
      { label: 'Jämför elavtal', href: '/elavtal/jamfor-elavtal', description: 'Räkna med den egna förbrukningen och avgifterna.' },
    ],
  }]
}))
