-- Gridex website pricing-only price-area resolver cache.
-- Scope: public website price preview only. Not facility, grid-owner or Ediel verification.

create table if not exists public.website_grid_area_price_areas (
  grid_area_code text primary key,
  grid_area_label text,
  price_area_code text not null check (price_area_code in ('SE1','SE2','SE3','SE4')),
  source text not null default 'manual',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.website_postal_code_price_areas (
  postal_code text primary key check (postal_code ~ '^\d{5}$'),
  city text,
  latitude numeric,
  longitude numeric,
  grid_area_code text,
  price_area_code text not null check (price_area_code in ('SE1','SE2','SE3','SE4')),
  confidence numeric not null default 0.85 check (confidence >= 0 and confidence <= 1),
  source text not null default 'papilite_arcgis',
  source_chain jsonb not null default '[]'::jsonb,
  raw_response jsonb not null default '{}'::jsonb,
  used_for text not null default 'pricing_preview_only' check (used_for = 'pricing_preview_only'),
  is_active boolean not null default true,
  looked_up_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.website_price_area_lookup_cache (
  id uuid primary key default gen_random_uuid(),
  postal_code text not null check (postal_code ~ '^\d{5}$'),
  city text,
  grid_area_code text,
  price_area_code text check (price_area_code in ('SE1','SE2','SE3','SE4')),
  lookup_status text not null default 'pending',
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  source text,
  source_chain jsonb not null default '[]'::jsonb,
  raw_response jsonb not null default '{}'::jsonb,
  error_message text,
  used_for text not null default 'pricing_preview_only' check (used_for = 'pricing_preview_only'),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists website_postal_code_price_areas_active_idx
  on public.website_postal_code_price_areas (postal_code, is_active, expires_at);

create index if not exists website_price_area_lookup_cache_postal_idx
  on public.website_price_area_lookup_cache (postal_code, created_at desc);

alter table public.website_grid_area_price_areas enable row level security;
alter table public.website_postal_code_price_areas enable row level security;
alter table public.website_price_area_lookup_cache enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'website_grid_area_price_areas'
      and policyname = 'service_role_manage_website_grid_area_price_areas'
  ) then
    create policy service_role_manage_website_grid_area_price_areas
      on public.website_grid_area_price_areas
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'website_postal_code_price_areas'
      and policyname = 'service_role_manage_website_postal_code_price_areas'
  ) then
    create policy service_role_manage_website_postal_code_price_areas
      on public.website_postal_code_price_areas
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'website_price_area_lookup_cache'
      and policyname = 'service_role_manage_website_price_area_lookup_cache'
  ) then
    create policy service_role_manage_website_price_area_lookup_cache
      on public.website_price_area_lookup_cache
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

insert into public.website_grid_area_price_areas
  (grid_area_code, grid_area_label, price_area_code, source, is_active)
values
  ('PIB', 'AB Piteenergi Pitebygden', 'SE1', 'esett_public_data_portal_221027', true),
  ('KKA', 'Affärsverken Elnät AB Karlskrona', 'SE4', 'esett_public_data_portal_221027', true),
  ('LED', 'Ale Elförening ek för Lilla Edet-Ale', 'SE3', 'esett_public_data_portal_221027', true),
  ('ALS', 'Alingsås Energi Nät Ab Alingsås', 'SE3', 'esett_public_data_portal_221027', true),
  ('AMS', 'Almnäs Bruk AB Almnäs', 'SE3', 'esett_public_data_portal_221027', true),
  ('ALV', 'Alvesta Elnät AB Alvesta Köping', 'SE4', 'esett_public_data_portal_221027', true),
  ('ARV', 'Arvika Teknik AB Arvika', 'SE3', 'esett_public_data_portal_221027', true),
  ('BAC', 'Baltic Cable AB BAC', 'SE4', 'esett_public_data_portal_221027', true),
  ('BEF', 'Bengtsfors Energi Nät AB Bengtsfors', 'SE3', 'esett_public_data_portal_221027', true),
  ('BRG', 'Bergs tingslags elektriska AB Berg', 'SE2', 'esett_public_data_portal_221027', true),
  ('KNS', 'BillerudKorsnäs Skog & Industri AB, Gävle Korsnäs', 'SE3', 'esett_public_data_portal_221027', true),
  ('BJR', 'Bjäre Kraft ek för Bjäre', 'SE4', 'esett_public_data_portal_221027', true),
  ('BKE', 'Bjärke Energi Ek. För. Bjärke', 'SE3', 'esett_public_data_portal_221027', true),
  ('BLI', 'Bliekevare Nät AB Bliekevare', 'SE2', 'esett_public_data_portal_221027', true),
  ('FRV', 'Blåsjön Nät AB Frostviken region', 'SE2', 'esett_public_data_portal_221027', true),
  ('KNP', 'Boda Nät ekonomiska förening Knäpplan', 'SE3', 'esett_public_data_portal_221027', true),
  ('BDN', 'Bodens Energi Nät AB Boden', 'SE1', 'esett_public_data_portal_221027', true),
  ('BOO', 'Boo Energi ek. för Boo', 'SE3', 'esett_public_data_portal_221027', true),
  ('BHM', 'Borgholm Energi Elnät AB Borgholm', 'SE4', 'esett_public_data_portal_221027', true),
  ('BRL', 'Borlänge Energi Elnät AB Borlänge', 'SE3', 'esett_public_data_portal_221027', true),
  ('BRS', 'Borås Elnät AB Borås', 'SE3', 'esett_public_data_portal_221027', true),
  ('BDL', 'Brittedals Elnät ek för Brittedal', 'SE4', 'esett_public_data_portal_221027', true),
  ('KVI', 'Brittedals Elnät ek för Kviinge', 'SE4', 'esett_public_data_portal_221027', true),
  ('BBN', 'Brobacken Nät AB Brobacken', 'SE1', 'esett_public_data_portal_221027', true),
  ('BMA', 'Bromölla Energi & Vatten AB Bromölla', 'SE4', 'esett_public_data_portal_221027', true),
  ('BLN', 'Brännliden Nät AB Brännliden', 'SE1', 'esett_public_data_portal_221027', true),
  ('KRS', 'C4 Elnät AB Kristianstad-Åhus', 'SE4', 'esett_public_data_portal_221027', true),
  ('CBR', 'Carlfors Bruk AB Carlfors Bruk', 'SE3', 'esett_public_data_portal_221027', true),
  ('GNF', 'Dala Energi Elnät AB Gagnef', 'SE3', 'esett_public_data_portal_221027', true),
  ('LER', 'Dala Energi Elnät AB Leksand-Rättvik', 'SE3', 'esett_public_data_portal_221027', true),
  ('STR', 'Dala Energi Elnät AB Säter', 'SE3', 'esett_public_data_portal_221027', true),
  ('DFS', 'Degerfors Energi AB Degerfors', 'SE3', 'esett_public_data_portal_221027', true),
  ('DLN', 'Dragaliden Net AB Dragaliden', 'SE1', 'esett_public_data_portal_221027', true),
  ('BLE', 'E.ON Energidistribution AB Blekinge', 'SE4', 'esett_public_data_portal_221027', true),
  ('DAN', 'E.ON Energidistribution AB Danderyd', 'SE3', 'esett_public_data_portal_221027', true),
  ('EKG', 'E.ON Energidistribution AB Enköping', 'SE3', 'esett_public_data_portal_221027', true),
  ('HLD', 'E.ON Energidistribution AB Halland', 'SE4', 'esett_public_data_portal_221027', true),
  ('HAM', 'E.ON Energidistribution AB Hammarstrand', 'SE2', 'esett_public_data_portal_221027', true),
  ('HRS', 'E.ON Energidistribution AB Harrsele region', 'SE2', 'esett_public_data_portal_221027', true),
  ('HJR', 'E.ON Energidistribution AB Hjälmaren Region', 'SE3', 'esett_public_data_portal_221027', true),
  ('KBR', 'E.ON Energidistribution AB Korsselbränna region', 'SE2', 'esett_public_data_portal_221027', true),
  ('KRF', 'E.ON Energidistribution AB Kramfors', 'SE2', 'esett_public_data_portal_221027', true),
  ('KBA', 'E.ON Energidistribution AB Kungsbacka', 'SE3', 'esett_public_data_portal_221027', true),
  ('LJV', 'E.ON Energidistribution AB Ljungan Övre region', 'SE2', 'esett_public_data_portal_221027', true),
  ('LYC', 'E.ON Energidistribution AB Lycksele region', 'SE2', 'esett_public_data_portal_221027', true),
  ('MMO', 'E.ON Energidistribution AB Malmö-Burlöv', 'SE4', 'esett_public_data_portal_221027', true),
  ('MEL', 'E.ON Energidistribution AB Medelpad Lokal', 'SE2', 'esett_public_data_portal_221027', true),
  ('NRL', 'E.ON Energidistribution AB Nerike Lokal', 'SE3', 'esett_public_data_portal_221027', true),
  ('NSF', 'E.ON Energidistribution AB Nissafors', 'SE3', 'esett_public_data_portal_221027', true),
  ('NRR', 'E.ON Energidistribution AB Nora Region', 'SE3', 'esett_public_data_portal_221027', true),
  ('NKR', 'E.ON Energidistribution AB Norrköping Region', 'SE3', 'esett_public_data_portal_221027', true),
  ('SKL', 'E.ON Energidistribution AB Skåne Landsbygd', 'SE4', 'esett_public_data_portal_221027', true),
  ('SKV', 'E.ON Energidistribution AB Skåne Västra Lokalnät', 'SE4', 'esett_public_data_portal_221027', true),
  ('SMN', 'E.ON Energidistribution AB Småland Norra lokalnät', 'SE3', 'esett_public_data_portal_221027', true),
  ('SML', 'E.ON Energidistribution AB Småland region', 'SE3', 'esett_public_data_portal_221027', true),
  ('SMS', 'E.ON Energidistribution AB Småland Södra', 'SE4', 'esett_public_data_portal_221027', true),
  ('SUR', 'E.ON Energidistribution AB Sundsvall region', 'SE2', 'esett_public_data_portal_221027', true),
  ('SYD', 'E.ON Energidistribution AB Sydsvenska region', 'SE4', 'esett_public_data_portal_221027', true),
  ('UPS', 'E.ON Energidistribution AB Uppland Södra', 'SE3', 'esett_public_data_portal_221027', true),
  ('ALL', 'E.ON Energidistribution AB Ådalen Lokal', 'SE2', 'esett_public_data_portal_221027', true),
  ('ADL', 'E.ON Energidistribution AB Ådalen region', 'SE2', 'esett_public_data_portal_221027', true),
  ('AKB', 'E.ON Energidistribution AB Åkersberga', 'SE3', 'esett_public_data_portal_221027', true),
  ('OLD', 'E.ON Energidistribution AB Öland', 'SE4', 'esett_public_data_portal_221027', true),
  ('OGO', 'E.ON Energidistribution AB Östra Götaland', 'SE3', 'esett_public_data_portal_221027', true),
  ('ESJ', 'Eksjö Elnät AB Eksjö', 'SE3', 'esett_public_data_portal_221027', true),
  ('BEV', 'Ellevio AB Bergvik region', 'SE2', 'esett_public_data_portal_221027', true),
  ('NBL', 'Ellevio AB Bohuslän Norra', 'SE3', 'esett_public_data_portal_221027', true),
  ('DAL', 'Ellevio AB Dalarna region', 'SE3', 'esett_public_data_portal_221027', true),
  ('EBN', 'Ellevio AB Edsbyn', 'SE2', 'esett_public_data_portal_221027', true),
  ('EKO', 'Ellevio AB Ekeröarna', 'SE3', 'esett_public_data_portal_221027', true),
  ('FBA', 'Ellevio AB Forsbacka Övre', 'SE3', 'esett_public_data_portal_221027', true),
  ('FLS', 'Ellevio AB Fågelsjö Region', 'SE2', 'esett_public_data_portal_221027', true),
  ('GRV', 'Ellevio AB Grönviken Region', 'SE2', 'esett_public_data_portal_221027', true),
  ('GBN', 'Ellevio AB Gullspångsbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('NHA', 'Ellevio AB Halland Norra', 'SE3', 'esett_public_data_portal_221027', true),
  ('HMM', 'Ellevio AB Hammarö', 'SE3', 'esett_public_data_portal_221027', true),
  ('HMR', 'Ellevio AB Hamra', 'SE2', 'esett_public_data_portal_221027', true),
  ('HDV', 'Ellevio AB Hudiksvall', 'SE2', 'esett_public_data_portal_221027', true),
  ('HAL', 'Ellevio AB Hälsingland', 'SE2', 'esett_public_data_portal_221027', true),
  ('HAR', 'Ellevio AB Hälsingland Region', 'SE2', 'esett_public_data_portal_221027', true),
  ('HJD', 'Ellevio AB Härjedalen region', 'SE2', 'esett_public_data_portal_221027', true),
  ('JDA', 'Ellevio AB Järva-Danderyd', 'SE3', 'esett_public_data_portal_221027', true),
  ('KEM', 'Ellevio AB Kema Nord region', 'SE2', 'esett_public_data_portal_221027', true),
  ('KOB', 'Ellevio AB Kopparbergsbyggden', 'SE3', 'esett_public_data_portal_221027', true),
  ('KUB', 'Ellevio AB Kungsbacka region', 'SE3', 'esett_public_data_portal_221027', true),
  ('LDG', 'Ellevio AB Lidingö', 'SE3', 'esett_public_data_portal_221027', true),
  ('LHD', 'Ellevio AB Lillhärdal Region', 'SE2', 'esett_public_data_portal_221027', true),
  ('MOR', 'Ellevio AB Mora-Orsa', 'SE3', 'esett_public_data_portal_221027', true),
  ('NHN', 'Ellevio AB Nynäshamn', 'SE3', 'esett_public_data_portal_221027', true),
  ('OBO', 'Ellevio AB Ockelbo', 'SE2', 'esett_public_data_portal_221027', true),
  ('ORT', 'Ellevio AB Orust-Tjörn', 'SE3', 'esett_public_data_portal_221027', true),
  ('STH', 'Ellevio AB Stockholm', 'SE3', 'esett_public_data_portal_221027', true),
  ('STO', 'Ellevio AB Stockholm Region', 'SE3', 'esett_public_data_portal_221027', true),
  ('TRJ', 'Ellevio AB Treje', 'SE3', 'esett_public_data_portal_221027', true),
  ('TRS', 'Ellevio AB Trängslet', 'SE3', 'esett_public_data_portal_221027', true),
  ('TBY', 'Ellevio AB Täby', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAT', 'Ellevio AB Vallentuna', 'SE3', 'esett_public_data_portal_221027', true),
  ('VNB', 'Ellevio AB Vansbro', 'SE3', 'esett_public_data_portal_221027', true),
  ('VLB', 'Ellevio AB Vålberg-Segerstad', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAL', 'Ellevio AB Värmland', 'SE3', 'esett_public_data_portal_221027', true),
  ('VML', 'Ellevio AB Värmland region', 'SE3', 'esett_public_data_portal_221027', true),
  ('AVD', 'Ellevio AB Älvdalen', 'SE3', 'esett_public_data_portal_221027', true),
  ('OCK', 'Ellevio AB Öckerö', 'SE3', 'esett_public_data_portal_221027', true),
  ('EBA', 'Emmaboda Elnät AB Emmaboda', 'SE4', 'esett_public_data_portal_221027', true),
  ('ESK', 'Eskilstuna Energi och Miljö Elnät AB Eskilstuna', 'SE3', 'esett_public_data_portal_221027', true),
  ('SBV', 'Eskilstuna Energi och Miljö Elnät AB Svalboviken', 'SE3', 'esett_public_data_portal_221027', true),
  ('FBN', 'Falbygdens Energi Nät AB Falbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('FBG', 'Falkenberg Energi AB Falkenberg', 'SE4', 'esett_public_data_portal_221027', true),
  ('FLN', 'Falu Elnät AB Falun', 'SE3', 'esett_public_data_portal_221027', true),
  ('FLO', 'Falu Elnät AB Falun nordost', 'SE3', 'esett_public_data_portal_221027', true),
  ('FPD', 'Filipstad Energinät AB Filipstad', 'SE3', 'esett_public_data_portal_221027', true),
  ('JUV', 'Fortum Sverige AB Juveln', 'SE2', 'esett_public_data_portal_221027', true),
  ('JPS', 'Fortum Sverige AB Järpströmmen region', 'SE2', 'esett_public_data_portal_221027', true),
  ('KRG', 'Fortum Sverige AB Krångede region', 'SE2', 'esett_public_data_portal_221027', true),
  ('LEV', 'Fortum Sverige AB Linnvasselv', 'SE2', 'esett_public_data_portal_221027', true),
  ('LAA', 'Fortum Sverige AB Långå', 'SE2', 'esett_public_data_portal_221027', true),
  ('MRR', 'Fortum Sverige AB Mörsil region', 'SE2', 'esett_public_data_portal_221027', true),
  ('GBT', 'Gabrielsberget Net AB Gabrielsberget', 'SE2', 'esett_public_data_portal_221027', true),
  ('GIV', 'Gislaved Energi Elnät AB Gislaved', 'SE3', 'esett_public_data_portal_221027', true),
  ('GTL', 'Gotlands Elnät AB Gotland', 'SE3', 'esett_public_data_portal_221027', true),
  ('GTP', 'Grästorp Energi ek för Grästorp', 'SE3', 'esett_public_data_portal_221027', true),
  ('FOB', 'Gävle Energi AB Forsbacka', 'SE3', 'esett_public_data_portal_221027', true),
  ('GVL', 'Gävle Energi AB Gävle', 'SE3', 'esett_public_data_portal_221027', true),
  ('HDS', 'Gävle Energi AB Hedesunda', 'SE3', 'esett_public_data_portal_221027', true),
  ('GBG', 'Göteborg Energi Nät AB Göteborg', 'SE3', 'esett_public_data_portal_221027', true),
  ('KKB', 'Götene Elförening Kinnekullebygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('HBO', 'Habo Kraft AB Habo', 'SE3', 'esett_public_data_portal_221027', true),
  ('HVI', 'Hallstaviks Elverk ek för Hallstavik', 'SE3', 'esett_public_data_portal_221027', true),
  ('HMD', 'Halmstads Energi och Miljö Nät AB Halmstad', 'SE4', 'esett_public_data_portal_221027', true),
  ('HVN', 'Havsnäs Elnät AB Havsnäs', 'SE2', 'esett_public_data_portal_221027', true),
  ('HMH', 'Hedemora Energi AB Hedemorahyttorna', 'SE3', 'esett_public_data_portal_221027', true),
  ('HLJ', 'Herrljunga Elektriska AB Herrljunga', 'SE3', 'esett_public_data_portal_221027', true),
  ('HJO', 'Hjo Energi AB Hjo', 'SE3', 'esett_public_data_portal_221027', true),
  ('HJM', 'Hjärtums Elförening ek för Hjärtum', 'SE3', 'esett_public_data_portal_221027', true),
  ('HOF', 'Hofors Elverk AB Hofors', 'SE3', 'esett_public_data_portal_221027', true),
  ('TOR', 'Hofors Elverk AB Torsåker', 'SE3', 'esett_public_data_portal_221027', true),
  ('VIK', 'Holmen Energi Elnät Varsvik', 'SE3', 'esett_public_data_portal_221027', true),
  ('HJN', 'Härjeåns Nät AB Härjeån', 'SE2', 'esett_public_data_portal_221027', true),
  ('ANE', 'Härjeåns Nät AB Ånge', 'SE2', 'esett_public_data_portal_221027', true),
  ('HSD', 'Härnösand Elnät AB Härnösand', 'SE2', 'esett_public_data_portal_221027', true),
  ('HRA', 'Härryda Energi AB Härryda', 'SE3', 'esett_public_data_portal_221027', true),
  ('HOG', 'Höganäs Energi AB Höganäs', 'SE4', 'esett_public_data_portal_221027', true),
  ('JUJ', 'Jukkasjärvi Sockens Belysningsförening Jukkasjärvi', 'SE1', 'esett_public_data_portal_221027', true),
  ('JMT', 'Jämtkraft Elnät AB Jämtland region', 'SE2', 'esett_public_data_portal_221027', true),
  ('JML', 'Jämtkraft Elnät AB Jämtlandsbygden', 'SE2', 'esett_public_data_portal_221027', true),
  ('LAN', 'Jämtkraft Elnät AB Länsterhöjden', 'SE2', 'esett_public_data_portal_221027', true),
  ('MAS', 'Jämtkraft Elnät AB Midskog-Åskälen', 'SE2', 'esett_public_data_portal_221027', true),
  ('JNK', 'Jönköping Energi Nät AB Jönköping', 'SE3', 'esett_public_data_portal_221027', true),
  ('KMR', 'Kalmar Energi Elnät AB Kalmar', 'SE4', 'esett_public_data_portal_221027', true),
  ('KBG', 'Karlsborgs Energi AB Karlsborg', 'SE3', 'esett_public_data_portal_221027', true),
  ('KHN', 'Karlshamn Energi Karlshamn', 'SE4', 'esett_public_data_portal_221027', true),
  ('KSA', 'Karlskoga Elnät AB Karlskoga', 'SE3', 'esett_public_data_portal_221027', true),
  ('KST', 'Karlstads El- och Stadsnät Karlstad', 'SE3', 'esett_public_data_portal_221027', true),
  ('ALD', 'Kraftnät Åland (SE) Åland', 'SE3', 'esett_public_data_portal_221027', true),
  ('BJK', 'Kraftringen Nät AB Björnekulla', 'SE4', 'esett_public_data_portal_221027', true),
  ('HLB', 'Kraftringen Nät AB Hallabro', 'SE4', 'esett_public_data_portal_221027', true),
  ('HOR', 'Kraftringen Nät AB Höör', 'SE4', 'esett_public_data_portal_221027', true),
  ('KPN', 'Kraftringen Nät AB Klippan', 'SE4', 'esett_public_data_portal_221027', true),
  ('LMA', 'Kraftringen Nät AB Lomma', 'SE4', 'esett_public_data_portal_221027', true),
  ('LUN', 'Kraftringen Nät AB Lund', 'SE4', 'esett_public_data_portal_221027', true),
  ('RSJ', 'Kraftringen Nät AB Ringsjö', 'SE4', 'esett_public_data_portal_221027', true),
  ('TOS', 'Kraftringen Nät AB Torsås', 'SE4', 'esett_public_data_portal_221027', true),
  ('KRH', 'Kristinehamns Elnät AB Kristinehamn', 'SE3', 'esett_public_data_portal_221027', true),
  ('KUV', 'Kungälv Energi AB Kungälv', 'SE3', 'esett_public_data_portal_221027', true),
  ('KFN', 'Kvarnforsen Nät AB Kvarnforsen', 'SE2', 'esett_public_data_portal_221027', true),
  ('KVM', 'Kvänumbygdens Energi ek. för Kvänum', 'SE3', 'esett_public_data_portal_221027', true),
  ('LKA', 'Landskrona Energi AB Landskrona', 'SE4', 'esett_public_data_portal_221027', true),
  ('LEH', 'Lehtirova Nät AB Lehtirova', 'SE1', 'esett_public_data_portal_221027', true),
  ('LRM', 'Lerum Energi AB Lerum', 'SE3', 'esett_public_data_portal_221027', true),
  ('LYS', 'LEVA i Lysekil AB Lysekil', 'SE3', 'esett_public_data_portal_221027', true),
  ('LDK', 'Lidköping Elnät Lidköping', 'SE3', 'esett_public_data_portal_221027', true),
  ('LDB', 'Linde Energi AB Lindesberg', 'SE3', 'esett_public_data_portal_221027', true),
  ('NKL', 'Linde Energi AB Närkes Kil', 'SE3', 'esett_public_data_portal_221027', true),
  ('LBY', 'Ljungby Energinät AB Ljungby', 'SE4', 'esett_public_data_portal_221027', true),
  ('LJD', 'Ljusdal Elnät AB Ljusdal', 'SE2', 'esett_public_data_portal_221027', true),
  ('KLK', 'LKAB Nät AB Kiruna LKAB', 'SE1', 'esett_public_data_portal_221027', true),
  ('MBT', 'LKAB Nät AB Malmberget LKAB', 'SE1', 'esett_public_data_portal_221027', true),
  ('LUL', 'Luleå Energi Elnät AB Luleå', 'SE1', 'esett_public_data_portal_221027', true),
  ('MLG', 'Malungs Elnät AB Malung', 'SE3', 'esett_public_data_portal_221027', true),
  ('TYS', 'Malungs Elnät AB Tyngsjö-Finnmarken', 'SE3', 'esett_public_data_portal_221027', true),
  ('URM', 'Malungs Elnät AB Upprämmen', 'SE3', 'esett_public_data_portal_221027', true),
  ('MBN', 'Markbygden Net AB Markbygden', 'SE1', 'esett_public_data_portal_221027', true),
  ('DBB', 'Markbygden Net Väst AB Dubblabergen', 'SE1', 'esett_public_data_portal_221027', true),
  ('SNM', 'Mellerst Skånes Kraft, ek för Skåne Mellersta', 'SE4', 'esett_public_data_portal_221027', true),
  ('MBY', 'Mjölby Kraftnät AB Mjölby', 'SE3', 'esett_public_data_portal_221027', true),
  ('MUL', 'Mullbergs Elnät AB Mullberget', 'SE2', 'esett_public_data_portal_221027', true),
  ('AOS', 'Mälarenergi AB Aros', 'SE3', 'esett_public_data_portal_221027', true),
  ('TLB', 'Mälarenergi Elnät AB Tillberga', 'SE3', 'esett_public_data_portal_221027', true),
  ('VLS', 'Mälarenergi Elnät AB Västmanland Södra', 'SE3', 'esett_public_data_portal_221027', true),
  ('MDL', 'Mölndal Energi Nät AB Mölndal', 'SE3', 'esett_public_data_portal_221027', true),
  ('JRA', 'Nacka Energi AB Järla', 'SE3', 'esett_public_data_portal_221027', true),
  ('SSJ', 'Njudung Energi Sävsjö AB Sävsjö', 'SE3', 'esett_public_data_portal_221027', true),
  ('VTL', 'Njudung Vetlanda Elnät AB Vetlanda', 'SE3', 'esett_public_data_portal_221027', true),
  ('NTE', 'Norrtälje Energi AB Norrtälje', 'SE3', 'esett_public_data_portal_221027', true),
  ('NSB', 'Nossebroortens Energi Ekonomisk Förening Nossebro', 'SE3', 'esett_public_data_portal_221027', true),
  ('NBR', 'Nybro Elnät AB Nybro', 'SE4', 'esett_public_data_portal_221027', true),
  ('SBK', 'Näckåns Elnät AB Sysslebäck', 'SE3', 'esett_public_data_portal_221027', true),
  ('NSO', 'Nässjö Affärsverk Elnät AB Nässjö', 'SE3', 'esett_public_data_portal_221027', true),
  ('OLS', 'Olofströms Kraft Nät AB Olofström', 'SE4', 'esett_public_data_portal_221027', true),
  ('OSD', 'Olseröds Elektriska Distributionsförening Olseröd', 'SE4', 'esett_public_data_portal_221027', true),
  ('OHN', 'Oskarshamn Energi Nät AB Oskarshamn tätort', 'SE4', 'esett_public_data_portal_221027', true),
  ('HFB', 'Ovako Sweden AB Hofors Bruk', 'SE3', 'esett_public_data_portal_221027', true),
  ('OXD', 'Oxelö Energi AB Oxelösund', 'SE3', 'esett_public_data_portal_221027', true),
  ('PTE', 'Partille Energi Nät AB Partille', 'SE3', 'esett_public_data_portal_221027', true),
  ('RBY', 'Ronneby Miljö & Teknik AB Ronneby', 'SE4', 'esett_public_data_portal_221027', true),
  ('RBF', 'Röbergsfjället Nät AB Röbergsfjället', 'SE3', 'esett_public_data_portal_221027', true),
  ('ROY', 'Rödeby Elverk ek för Rödeby', 'SE4', 'esett_public_data_portal_221027', true),
  ('HBY', 'Sala-Heby Energi Elnät AB Heby', 'SE3', 'esett_public_data_portal_221027', true),
  ('SAH', 'Sala-Heby Energi Elnät AB Sala-Hyttan', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBK', 'Sala-Heby Energi Elnät AB Västerbykil', 'SE3', 'esett_public_data_portal_221027', true),
  ('SHT', 'Sandhult-Sandared Elektriska ek för Sandhult-Sandared', 'SE3', 'esett_public_data_portal_221027', true),
  ('SDV', 'Sandviken Energi Elnät AB Sandviken', 'SE3', 'esett_public_data_portal_221027', true),
  ('OFB', 'Sandviken Energi Elnät AB Österfärnebo', 'SE3', 'esett_public_data_portal_221027', true),
  ('SGS', 'SEVAB Nät AB Strängnäs Tätort', 'SE3', 'esett_public_data_portal_221027', true),
  ('SID', 'Sidensjö Vindkraft Elnät AB Sidensjö', 'SE2', 'esett_public_data_portal_221027', true),
  ('SJN', 'Sjisjka Nät AB Sjisjka', 'SE1', 'esett_public_data_portal_221027', true),
  ('SJO', 'Sjogerstads Elektriska Distributionsförening Sjogerstad', 'SE3', 'esett_public_data_portal_221027', true),
  ('SJB', 'Sjöbo Elnät AB Sjöbo', 'SE4', 'esett_public_data_portal_221027', true),
  ('SKA', 'Skara Energi AB Skara', 'SE3', 'esett_public_data_portal_221027', true),
  ('BYG', 'Skellefteå Kraft Elnät AB Bygdeå-Robertsfors', 'SE2', 'esett_public_data_portal_221027', true),
  ('LYX', 'Skellefteå Kraft Elnät AB Lyckselebygden', 'SE2', 'esett_public_data_portal_221027', true),
  ('SKT', 'Skellefteå Kraft Elnät AB Skellefteå', 'SE1', 'esett_public_data_portal_221027', true),
  ('SKF', 'Skellefteå Kraft Elnät AB Skellefteå region', 'SE1', 'esett_public_data_portal_221027', true),
  ('SOL', 'Skellefteå Kraft Elnät AB Solberg region', 'SE2', 'esett_public_data_portal_221027', true),
  ('VDN', 'Skellefteå Kraft Elnät AB Vindeln', 'SE2', 'esett_public_data_portal_221027', true),
  ('SKP', 'Skurups Elverk AB Skurup', 'SE4', 'esett_public_data_portal_221027', true),
  ('SBR', 'Skyllbergs Bruk AB Skyllbergs Bruk', 'SE3', 'esett_public_data_portal_221027', true),
  ('SKN', 'Skånska Energi Nät AB Skånska', 'SE4', 'esett_public_data_portal_221027', true),
  ('SKD', 'Skövde Energi Elnät AB Skövde', 'SE3', 'esett_public_data_portal_221027', true),
  ('SMB', 'Smedjebacken Energi Nät AB Smedjebacken', 'SE3', 'esett_public_data_portal_221027', true),
  ('SOT', 'Sollentuna Energi AB Sollentuna', 'SE3', 'esett_public_data_portal_221027', true),
  ('SFP', 'Staffanstorps Energi AB Staffanstorp', 'SE4', 'esett_public_data_portal_221027', true),
  ('STF', 'Stensjön Kraft AB Stensjöfallet region', 'SE2', 'esett_public_data_portal_221027', true),
  ('SRF', 'Sturefors Eldistribution AB Sturefors', 'SE3', 'esett_public_data_portal_221027', true),
  ('SUV', 'Sundsvall Elnät AB Sundsvall tätort', 'SE2', 'esett_public_data_portal_221027', true),
  ('ARN', 'Swedavia Energi AB Stockholm-Arlanda', 'SE3', 'esett_public_data_portal_221027', true),
  ('AJG', 'Svenska kraftnät Ajaure-Grundfors', 'SE2', 'esett_public_data_portal_221027', true),
  ('KON', 'Svenska kraftnät Konti-Skan st', 'SE3', 'esett_public_data_portal_221027', true),
  ('PLT', 'Svenska kraftnät NordBalt', 'SE4', 'esett_public_data_portal_221027', true),
  ('POL', 'Svenska kraftnät Polen', 'SE4', 'esett_public_data_portal_221027', true),
  ('ST1', 'Svenska kraftnät Stamnät Snittområde 1', 'SE1', 'esett_public_data_portal_221027', true),
  ('ST2', 'Svenska kraftnät Stamnät Snittområde 2', 'SE2', 'esett_public_data_portal_221027', true),
  ('ST3', 'Svenska kraftnät Stamnät Snittområde 3', 'SE3', 'esett_public_data_portal_221027', true),
  ('ST4', 'Svenska kraftnät Stamnät Snittområde 4', 'SE4', 'esett_public_data_portal_221027', true),
  ('SWP', 'Svenska kraftnät SwePollink', 'SE4', 'esett_public_data_portal_221027', true),
  ('TYV', 'Svenska kraftnät Tyskland väst', 'SE4', 'esett_public_data_portal_221027', true),
  ('SHN', 'Söderhamn Elnät AB Söderhamn', 'SE2', 'esett_public_data_portal_221027', true),
  ('LHM', 'Södra Hallands Kraft ekonomisk förening Laholm', 'SE4', 'esett_public_data_portal_221027', true),
  ('SBG', 'Sölvesborg Energi och Vatten AB Sölvesborg', 'SE4', 'esett_public_data_portal_221027', true),
  ('SBL', 'Sörbylunds Elnät AB Sörbylund', 'SE3', 'esett_public_data_portal_221027', true),
  ('KHB', 'Tekniska verken i Katrineholm Nät AB Katrineholmsbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('LNK', 'Tekniska verken Linköping Nät AB Linköping', 'SE3', 'esett_public_data_portal_221027', true),
  ('SDT', 'Telge Nät AB Södertälje', 'SE3', 'esett_public_data_portal_221027', true),
  ('TIB', 'Tibro Energi AB Tibro', 'SE3', 'esett_public_data_portal_221027', true),
  ('THM', 'Tidaholms Elnät AB Tidaholm', 'SE3', 'esett_public_data_portal_221027', true),
  ('TNS', 'Tranås Energi Elnät AB Tranås', 'SE3', 'esett_public_data_portal_221027', true),
  ('TBG', 'Trelleborgs kommun Trelleborg', 'SE4', 'esett_public_data_portal_221027', true),
  ('TRH', 'Trollhättan Energi Elnät AB Trollhättan', 'SE3', 'esett_public_data_portal_221027', true),
  ('TRE', 'Töre Energi ek för Töre', 'SE1', 'esett_public_data_portal_221027', true),
  ('UVA', 'Uddevalla Energi Elnät AB Uddevalla', 'SE3', 'esett_public_data_portal_221027', true),
  ('UHN', 'Ulricehamns Energi AB Ulricehamn', 'SE3', 'esett_public_data_portal_221027', true),
  ('UMA', 'Umeå Energi Elnät AB Umeå', 'SE2', 'esett_public_data_portal_221027', true),
  ('UME', 'Umeå Energi Elnät AB Umeå region', 'SE2', 'esett_public_data_portal_221027', true),
  ('BJL', 'Upplands Energi Björklinge', 'SE3', 'esett_public_data_portal_221027', true),
  ('VGD', 'Vaggeryds Elverk Vaggeryd', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAB', 'Vallebygdens Energi ek för Vallebygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAR', 'Vara Energi ek.för Vara', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBG', 'Varberg Energi AB Varberg', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBN', 'Varbergsortens Elkraft ek för Varbergsorten Norra', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBS', 'Varbergsortens Elkraft ek för Varbergsorten Södra', 'SE3', 'esett_public_data_portal_221027', true),
  ('ARD', 'Vattenfall Eldistribution AB Ardala', 'SE3', 'esett_public_data_portal_221027', true),
  ('AJB', 'Vattenfall Eldistribution AB Arvidsjaurbygden', 'SE1', 'esett_public_data_portal_221027', true),
  ('AVE', 'Vattenfall Eldistribution AB Avesta', 'SE3', 'esett_public_data_portal_221027', true),
  ('AVR', 'Vattenfall Eldistribution AB Avesta region', 'SE3', 'esett_public_data_portal_221027', true),
  ('BGS', 'Vattenfall Eldistribution AB Bergslagen region', 'SE3', 'esett_public_data_portal_221027', true),
  ('BGO', 'Vattenfall Eldistribution AB Bergslagen Östra', 'SE3', 'esett_public_data_portal_221027', true),
  ('BLT', 'Vattenfall Eldistribution AB Björnlandet', 'SE2', 'esett_public_data_portal_221027', true),
  ('DAD', 'Vattenfall Eldistribution AB Dalsland med omnejd', 'SE3', 'esett_public_data_portal_221027', true),
  ('DRV', 'Vattenfall Eldistribution AB Drefviken', 'SE3', 'esett_public_data_portal_221027', true),
  ('FSB', 'Vattenfall Eldistribution AB Finspångsbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('FLE', 'Vattenfall Eldistribution AB Flen', 'SE3', 'esett_public_data_portal_221027', true),
  ('FMD', 'Vattenfall Eldistribution AB Främmestad', 'SE3', 'esett_public_data_portal_221027', true),
  ('GAM', 'Vattenfall Eldistribution AB Gammelstilla', 'SE3', 'esett_public_data_portal_221027', true),
  ('GAB', 'Vattenfall Eldistribution AB Garpenberg', 'SE3', 'esett_public_data_portal_221027', true),
  ('GDB', 'Vattenfall Eldistribution AB Gideobygden', 'SE2', 'esett_public_data_portal_221027', true),
  ('GTA', 'Vattenfall Eldistribution AB Göta', 'SE3', 'esett_public_data_portal_221027', true),
  ('HDL', 'Vattenfall Eldistribution AB Horndal', 'SE3', 'esett_public_data_portal_221027', true),
  ('HDG', 'Vattenfall Eldistribution AB Huddinge', 'SE3', 'esett_public_data_portal_221027', true),
  ('HUV', 'Vattenfall Eldistribution AB Huvudsta', 'SE3', 'esett_public_data_portal_221027', true),
  ('ING', 'Vattenfall Eldistribution AB Ingarö', 'SE3', 'esett_public_data_portal_221027', true),
  ('KAB', 'Vattenfall Eldistribution AB Kalixbygden', 'SE1', 'esett_public_data_portal_221027', true),
  ('KND', 'Vattenfall Eldistribution AB Kind', 'SE3', 'esett_public_data_portal_221027', true),
  ('LGR', 'Vattenfall Eldistribution AB Lillgrund', 'SE4', 'esett_public_data_portal_221027', true),
  ('LAO', 'Vattenfall Eldistribution AB Luleälven Övre', 'SE1', 'esett_public_data_portal_221027', true),
  ('MAF', 'Vattenfall Eldistribution AB Malmfälten', 'SE1', 'esett_public_data_portal_221027', true),
  ('MSD', 'Vattenfall Eldistribution AB Marstrand', 'SE3', 'esett_public_data_portal_221027', true),
  ('VFM', 'Vattenfall Eldistribution AB Mellansverige region', 'SE3', 'esett_public_data_portal_221027', true),
  ('MYN', 'Vattenfall Eldistribution AB Myråsen', 'SE3', 'esett_public_data_portal_221027', true),
  ('NOB', 'Vattenfall Eldistribution AB Norberg', 'SE3', 'esett_public_data_portal_221027', true),
  ('VFN', 'Vattenfall Eldistribution AB Norrbotten region', 'SE1', 'esett_public_data_portal_221027', true),
  ('NYK', 'Vattenfall Eldistribution AB Nyköping', 'SE3', 'esett_public_data_portal_221027', true),
  ('NYD', 'Vattenfall Eldistribution AB Nyköping Landsbygd', 'SE3', 'esett_public_data_portal_221027', true),
  ('RSK', 'Vattenfall Eldistribution AB Roslagskusten', 'SE3', 'esett_public_data_portal_221027', true),
  ('SIG', 'Vattenfall Eldistribution AB Sigtuna', 'SE3', 'esett_public_data_portal_221027', true),
  ('SHD', 'Vattenfall Eldistribution AB Sjuhärad', 'SE3', 'esett_public_data_portal_221027', true),
  ('SKR', 'Vattenfall Eldistribution AB Skillingaryd', 'SE3', 'esett_public_data_portal_221027', true),
  ('SLD', 'Vattenfall Eldistribution AB Skövde Landsbygd', 'SE3', 'esett_public_data_portal_221027', true),
  ('SGD', 'Vattenfall Eldistribution AB Stenungsund', 'SE3', 'esett_public_data_portal_221027', true),
  ('SYM', 'Vattenfall Eldistribution AB Sydmälaren', 'SE3', 'esett_public_data_portal_221027', true),
  ('SFE', 'Vattenfall Eldistribution AB Säffle', 'SE3', 'esett_public_data_portal_221027', true),
  ('TNN', 'Vattenfall Eldistribution AB Tornedalen Nedre', 'SE1', 'esett_public_data_portal_221027', true),
  ('TDO', 'Vattenfall Eldistribution AB Tornedalen Övre', 'SE1', 'esett_public_data_portal_221027', true),
  ('TUM', 'Vattenfall Eldistribution AB Tumba', 'SE3', 'esett_public_data_portal_221027', true),
  ('TYR', 'Vattenfall Eldistribution AB Tyresö', 'SE3', 'esett_public_data_portal_221027', true),
  ('UMD', 'Vattenfall Eldistribution AB Umeälven Nedre', 'SE2', 'esett_public_data_portal_221027', true),
  ('UMN', 'Vattenfall Eldistribution AB Umeälven region', 'SE2', 'esett_public_data_portal_221027', true),
  ('UMO', 'Vattenfall Eldistribution AB Umeälven Övre', 'SE2', 'esett_public_data_portal_221027', true),
  ('UPN', 'Vattenfall Eldistribution AB Uppland Norra', 'SE3', 'esett_public_data_portal_221027', true),
  ('UPV', 'Vattenfall Eldistribution AB Uppland Västra', 'SE3', 'esett_public_data_portal_221027', true),
  ('UPO', 'Vattenfall Eldistribution AB Uppland Östra', 'SE3', 'esett_public_data_portal_221027', true),
  ('UPP', 'Vattenfall Eldistribution AB Uppsala', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAG', 'Vattenfall Eldistribution AB Vagnhärad', 'SE3', 'esett_public_data_portal_221027', true),
  ('VDM', 'Vattenfall Eldistribution AB Vedum', 'SE3', 'esett_public_data_portal_221027', true),
  ('VMA', 'Vattenfall Eldistribution AB Vilhelmina', 'SE2', 'esett_public_data_portal_221027', true),
  ('VIG', 'Vattenfall Eldistribution AB Vingåkersbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('VMD', 'Vattenfall Eldistribution AB Värmdö', 'SE3', 'esett_public_data_portal_221027', true),
  ('VRO', 'Vattenfall Eldistribution AB Värö region', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAD', 'Vattenfall Eldistribution AB Västanhede', 'SE3', 'esett_public_data_portal_221027', true),
  ('VFV', 'Vattenfall Eldistribution AB Västsverige region', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAN', 'Vattenfall Eldistribution AB Vätterbygden', 'SE3', 'esett_public_data_portal_221027', true),
  ('AML', 'Vattenfall Eldistribution AB Åmål', 'SE3', 'esett_public_data_portal_221027', true),
  ('ANN', 'Vattenfall Eldistribution AB Ånge region', 'SE2', 'esett_public_data_portal_221027', true),
  ('AMN', 'Vattenfall Eldistribution AB Ångermanälven region', 'SE2', 'esett_public_data_portal_221027', true),
  ('ANG', 'Vattenfall Eldistribution AB Årjäng', 'SE3', 'esett_public_data_portal_221027', true),
  ('ABB', 'Vattenfall Eldistribution AB Älvsbybygden', 'SE1', 'esett_public_data_portal_221027', true),
  ('OHM', 'Vattenfall Eldistribution AB Östhammar', 'SE3', 'esett_public_data_portal_221027', true),
  ('VFO', 'Vattenfall Eldistribution AB Östsverige region', 'SE3', 'esett_public_data_portal_221027', true),
  ('JKE', 'Vattenfall Kraftgården AB Järkvissle', 'SE2', 'esett_public_data_portal_221027', true),
  ('NFO', 'Vattenfall Kraftgården AB Nämforsen region', 'SE2', 'esett_public_data_portal_221027', true),
  ('STU', 'Vattenfall Kraftgården AB Stugun region', 'SE2', 'esett_public_data_portal_221027', true),
  ('VGF', 'Viggafors Elektriska Andelsförening Upa Viggafors', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBY', 'Vimmerby Energi Nät AB Vimmerby', 'SE3', 'esett_public_data_portal_221027', true),
  ('GLG', 'Vindpark Vänern Drift AB Gässlingegrund', 'SE3', 'esett_public_data_portal_221027', true),
  ('MAI', 'VänerEnergi AB Mariestad', 'SE3', 'esett_public_data_portal_221027', true),
  ('TBA', 'VänerEnergi AB Töreboda', 'SE3', 'esett_public_data_portal_221027', true),
  ('VMO', 'Värnamo Elnät AB Värnamo', 'SE4', 'esett_public_data_portal_221027', true),
  ('FGA', 'Västerbergslagens Elnät AB Fagersta', 'SE3', 'esett_public_data_portal_221027', true),
  ('VAS', 'Västerbergslagens Elnät AB Västanfors', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBL', 'Västerbergslagens Elnät AB Västerbergslagen', 'SE3', 'esett_public_data_portal_221027', true),
  ('VBR', 'Västerbergslagens Elnät AB Västerbergslagen Regionalnät', 'SE3', 'esett_public_data_portal_221027', true),
  ('VVI', 'Västerviks Kraft Elnät AB Västervik', 'SE3', 'esett_public_data_portal_221027', true),
  ('ORV', 'Västra Orusts Energitjänst ek. för. Orust Västra', 'SE3', 'esett_public_data_portal_221027', true),
  ('VXO', 'Växjö Energi Elnät AB Växjö', 'SE4', 'esett_public_data_portal_221027', true),
  ('YST', 'Ystad Energi AB Ystad', 'SE4', 'esett_public_data_portal_221027', true),
  ('ALM', 'Ålem Energi AB Ålem', 'SE4', 'esett_public_data_portal_221027', true),
  ('ARS', 'Årsunda Kraft-o Belysningsförening Upa Årsunda', 'SE3', 'esett_public_data_portal_221027', true),
  ('ASL', 'Åsele Elnät AB Åsele', 'SE2', 'esett_public_data_portal_221027', true),
  ('ASK', 'Åskälen Vindkraft Elnät AB Åskälen', 'SE2', 'esett_public_data_portal_221027', true),
  ('HBG', 'Öresundskraft AB Helsingborg', 'SE4', 'esett_public_data_portal_221027', true),
  ('MRP', 'Öresundskraft AB Mörarp', 'SE4', 'esett_public_data_portal_221027', true),
  ('NVS', 'Öresundskraft AB Nordvästra Skåne', 'SE4', 'esett_public_data_portal_221027', true),
  ('SKH', 'Öresundskraft AB Skåne-Halland region', 'SE4', 'esett_public_data_portal_221027', true),
  ('AHB', 'Öresundskraft AB Ängelholmsbygden', 'SE4', 'esett_public_data_portal_221027', true),
  ('SIH', 'Österlens Kraft AB Simrishamn', 'SE4', 'esett_public_data_portal_221027', true),
  ('OLN', 'Österlens Kraft AB Österlen', 'SE4', 'esett_public_data_portal_221027', true),
  ('DAP', 'Östra Kinds Elkraft Dalstorp', 'SE3', 'esett_public_data_portal_221027', true),
  ('TDN', 'Övertorneå Energi AB Tornedalen', 'SE1', 'esett_public_data_portal_221027', true),
  ('DOF', 'Övik Energi Nät AB Domsjö Fabriksområde', 'SE2', 'esett_public_data_portal_221027', true),
  ('OVK', 'Övik Energi Nät AB Örnsköldsvik', 'SE2', 'esett_public_data_portal_221027', true)
on conflict (grid_area_code) do update set
  grid_area_label = excluded.grid_area_label,
  price_area_code = excluded.price_area_code,
  source = excluded.source,
  is_active = excluded.is_active,
  updated_at = now();
